
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action tbrQuit;
	private global::Gtk.Action tbrPreferences;
	private global::Gtk.Action tbrHelp;
	private global::Gtk.Alignment alignment1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.Alignment alignment2;
	private global::Gtk.Toolbar tbrMain;
	private global::Gtk.Alignment alignment3;
	private global::Gtk.Notebook nbkMain;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Alignment alignment9;
	private global::Gtk.Expander expErrorToolsSetup;
	private global::Gtk.Alignment alignment11;
	private global::Gtk.Frame frame3;
	private global::Gtk.Alignment GtkAlignment3;
	private global::Gtk.Table tblErrorTools1;
	private global::Gtk.Alignment alignment12;
	private global::Gtk.Label lblDisplayErrorLog1;
	private global::Gtk.Alignment alignment14;
	private global::Gtk.Label lblDisplayErrorMessage1;
	private global::Gtk.Alignment alignment15;
	private global::Gtk.Label lblDisplayErrorLog2;
	private global::Gtk.Alignment alignment16;
	private global::Gtk.Label lblDisplayErrorLog3;
	private global::Gtk.Alignment alignment17;
	private global::Gtk.Label lblDisplayErrorLog4;
	private global::Gtk.Alignment alignment18;
	private global::Gtk.CheckButton cbxUseErrorLog;
	private global::Gtk.Alignment alignment19;
	private global::Gtk.Entry txtErrorLogFileName;
	private global::Gtk.FileChooserButton fcUserDataPath;
	private global::Gtk.Entry txtBugTrackingURL;
	private global::Gtk.Entry txtNewTicketURL;
	private global::Gtk.Label GtkLabel6;
	private global::Gtk.Label GtkLabel7;
	private global::Gtk.Alignment alignment5;
	private global::Gtk.Table tblErrorTools;
	private global::Gtk.Alignment alignment13;
	private global::Gtk.Button btnErrorLogDisplay;
	private global::Gtk.Alignment alignment6;
	private global::Gtk.Label lblDisplayErrorMessage;
	private global::Gtk.Alignment alignment7;
	private global::Gtk.Button btnErrorDialogDisplay;
	private global::Gtk.Alignment alignment8;
	private global::Gtk.Label lblDisplayErrorLog;
	private global::Gtk.Entry txtErrorMessage;
	private global::Gtk.Label lblErrorTools;
	private global::Gtk.Label label2;
	private global::Gtk.Label label3;
	private global::Gtk.Label label4;
	private global::Gtk.Alignment alignment10;
	private global::Gtk.Label label5;
	private global::Gtk.Alignment alignment4;
	private global::Gtk.Statusbar sbrMain;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.tbrQuit = new global::Gtk.Action ("tbrQuit", null, null, "gtk-quit");
		w1.Add (this.tbrQuit, null);
		this.tbrPreferences = new global::Gtk.Action ("tbrPreferences", null, null, "gtk-preferences");
		w1.Add (this.tbrPreferences, null);
		this.tbrHelp = new global::Gtk.Action ("tbrHelp", null, null, "gtk-help");
		w1.Add (this.tbrHelp, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MonoTools Testing Application");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Dialog);
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		// Container child alignment1.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		// Container child alignment2.Gtk.Container+ContainerChild
		this.UIManager.AddUiFromString ("<ui><toolbar name=\'tbrMain\'><toolitem name=\'tbrQuit\' action=\'tbrQuit\'/><toolitem " +
			"name=\'tbrPreferences\' action=\'tbrPreferences\'/><toolitem name=\'tbrHelp\' action=\'" +
			"tbrHelp\'/></toolbar></ui>");
		this.tbrMain = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/tbrMain")));
		this.tbrMain.Name = "tbrMain";
		this.tbrMain.ShowArrow = false;
		this.alignment2.Add (this.tbrMain);
		this.vbox1.Add (this.alignment2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment3.Name = "alignment3";
		// Container child alignment3.Gtk.Container+ContainerChild
		this.nbkMain = new global::Gtk.Notebook ();
		this.nbkMain.CanFocus = true;
		this.nbkMain.Name = "nbkMain";
		this.nbkMain.CurrentPage = 0;
		// Container child nbkMain.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.alignment9 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment9.Name = "alignment9";
		this.alignment9.LeftPadding = ((uint)(8));
		this.alignment9.TopPadding = ((uint)(8));
		this.alignment9.RightPadding = ((uint)(8));
		this.alignment9.BottomPadding = ((uint)(4));
		// Container child alignment9.Gtk.Container+ContainerChild
		this.expErrorToolsSetup = new global::Gtk.Expander (null);
		this.expErrorToolsSetup.CanFocus = true;
		this.expErrorToolsSetup.Name = "expErrorToolsSetup";
		// Container child expErrorToolsSetup.Gtk.Container+ContainerChild
		this.alignment11 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment11.Name = "alignment11";
		// Container child alignment11.Gtk.Container+ContainerChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.RightPadding = ((uint)(5));
		this.GtkAlignment3.BorderWidth = ((uint)(8));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.tblErrorTools1 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
		this.tblErrorTools1.Name = "tblErrorTools1";
		this.tblErrorTools1.RowSpacing = ((uint)(6));
		this.tblErrorTools1.ColumnSpacing = ((uint)(6));
		// Container child tblErrorTools1.Gtk.Table+TableChild
		this.alignment12 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
		this.alignment12.Name = "alignment12";
		// Container child alignment12.Gtk.Container+ContainerChild
		this.lblDisplayErrorLog1 = new global::Gtk.Label ();
		this.lblDisplayErrorLog1.Name = "lblDisplayErrorLog1";
		this.lblDisplayErrorLog1.LabelProp = global::Mono.Unix.Catalog.GetString ("Error Log File Name:");
		this.lblDisplayErrorLog1.SingleLineMode = true;
		this.alignment12.Add (this.lblDisplayErrorLog1);
		this.tblErrorTools1.Add (this.alignment12);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tblErrorTools1 [this.alignment12]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblErrorTools1.Gtk.Table+TableChild
		this.alignment14 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
		this.alignment14.Name = "alignment14";
		// Container child alignment14.Gtk.Container+ContainerChild
		this.lblDisplayErrorMessage1 = new global::Gtk.Label ();
		this.lblDisplayErrorMessage1.Name = "lblDisplayErrorMessage1";
		this.lblDisplayErrorMessage1.LabelProp = global::Mono.Unix.Catalog.GetString ("User Error Log:");
		this.lblDisplayErrorMessage1.SingleLineMode = true;
		this.alignment14.Add (this.lblDisplayErrorMessage1);
		this.tblErrorTools1.Add (this.alignment14);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tblErrorTools1 [this.alignment14]));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblErrorTools1.Gtk.Table+TableChild
		this.alignment15 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
		this.alignment15.Name = "alignment15";
		// Container child alignment15.Gtk.Container+ContainerChild
		this.lblDisplayErrorLog2 = new global::Gtk.Label ();
		this.lblDisplayErrorLog2.Name = "lblDisplayErrorLog2";
		this.lblDisplayErrorLog2.LabelProp = global::Mono.Unix.Catalog.GetString ("Bug Tracking URL:");
		this.lblDisplayErrorLog2.SingleLineMode = true;
		this.alignment15.Add (this.lblDisplayErrorLog2);
		this.tblErrorTools1.Add (this.alignment15);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblErrorTools1 [this.alignment15]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblErrorTools1.Gtk.Table+TableChild
		this.alignment16 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
		this.alignment16.Name = "alignment16";
		// Container child alignment16.Gtk.Container+ContainerChild
		this.lblDisplayErrorLog3 = new global::Gtk.Label ();
		this.lblDisplayErrorLog3.Name = "lblDisplayErrorLog3";
		this.lblDisplayErrorLog3.LabelProp = global::Mono.Unix.Catalog.GetString ("New Ticket URL:");
		this.lblDisplayErrorLog3.SingleLineMode = true;
		this.alignment16.Add (this.lblDisplayErrorLog3);
		this.tblErrorTools1.Add (this.alignment16);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tblErrorTools1 [this.alignment16]));
		w11.TopAttach = ((uint)(3));
		w11.BottomAttach = ((uint)(4));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblErrorTools1.Gtk.Table+TableChild
		this.alignment17 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
		this.alignment17.Name = "alignment17";
		// Container child alignment17.Gtk.Container+ContainerChild
		this.lblDisplayErrorLog4 = new global::Gtk.Label ();
		this.lblDisplayErrorLog4.Name = "lblDisplayErrorLog4";
		this.lblDisplayErrorLog4.LabelProp = global::Mono.Unix.Catalog.GetString ("User Data Path:");
		this.lblDisplayErrorLog4.SingleLineMode = true;
		this.alignment17.Add (this.lblDisplayErrorLog4);
		this.tblErrorTools1.Add (this.alignment17);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblErrorTools1 [this.alignment17]));
		w13.TopAttach = ((uint)(4));
		w13.BottomAttach = ((uint)(5));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblErrorTools1.Gtk.Table+TableChild
		this.alignment18 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment18.Name = "alignment18";
		// Container child alignment18.Gtk.Container+ContainerChild
		this.cbxUseErrorLog = new global::Gtk.CheckButton ();
		this.cbxUseErrorLog.CanFocus = true;
		this.cbxUseErrorLog.Name = "cbxUseErrorLog";
		this.cbxUseErrorLog.Label = "";
		this.cbxUseErrorLog.Active = true;
		this.cbxUseErrorLog.DrawIndicator = true;
		this.cbxUseErrorLog.UseUnderline = true;
		this.alignment18.Add (this.cbxUseErrorLog);
		this.tblErrorTools1.Add (this.alignment18);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tblErrorTools1 [this.alignment18]));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(2));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblErrorTools1.Gtk.Table+TableChild
		this.alignment19 = new global::Gtk.Alignment (0F, 0.5F, 0.01F, 1F);
		this.alignment19.Name = "alignment19";
		// Container child alignment19.Gtk.Container+ContainerChild
		this.txtErrorLogFileName = new global::Gtk.Entry ();
		this.txtErrorLogFileName.WidthRequest = 175;
		this.txtErrorLogFileName.CanFocus = true;
		this.txtErrorLogFileName.Name = "txtErrorLogFileName";
		this.txtErrorLogFileName.Text = global::Mono.Unix.Catalog.GetString ("ErrorLog.txt");
		this.txtErrorLogFileName.IsEditable = true;
		this.alignment19.Add (this.txtErrorLogFileName);
		this.tblErrorTools1.Add (this.alignment19);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tblErrorTools1 [this.alignment19]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblErrorTools1.Gtk.Table+TableChild
		this.fcUserDataPath = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Set the path to use as the \\\"User Data Path\\\""), ((global::Gtk.FileChooserAction)(2)));
		this.fcUserDataPath.Name = "fcUserDataPath";
		this.tblErrorTools1.Add (this.fcUserDataPath);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tblErrorTools1 [this.fcUserDataPath]));
		w18.TopAttach = ((uint)(4));
		w18.BottomAttach = ((uint)(5));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XOptions = ((global::Gtk.AttachOptions)(7));
		w18.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child tblErrorTools1.Gtk.Table+TableChild
		this.txtBugTrackingURL = new global::Gtk.Entry ();
		this.txtBugTrackingURL.CanFocus = true;
		this.txtBugTrackingURL.Name = "txtBugTrackingURL";
		this.txtBugTrackingURL.Text = global::Mono.Unix.Catalog.GetString ("http://mono-project.com/Main_Page");
		this.txtBugTrackingURL.IsEditable = true;
		this.tblErrorTools1.Add (this.txtBugTrackingURL);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tblErrorTools1 [this.txtBugTrackingURL]));
		w19.TopAttach = ((uint)(2));
		w19.BottomAttach = ((uint)(3));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		w19.XOptions = ((global::Gtk.AttachOptions)(7));
		w19.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child tblErrorTools1.Gtk.Table+TableChild
		this.txtNewTicketURL = new global::Gtk.Entry ();
		this.txtNewTicketURL.CanFocus = true;
		this.txtNewTicketURL.Name = "txtNewTicketURL";
		this.txtNewTicketURL.Text = global::Mono.Unix.Catalog.GetString ("http://monodevelop.com/");
		this.txtNewTicketURL.IsEditable = true;
		this.tblErrorTools1.Add (this.txtNewTicketURL);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tblErrorTools1 [this.txtNewTicketURL]));
		w20.TopAttach = ((uint)(3));
		w20.BottomAttach = ((uint)(4));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(7));
		w20.YOptions = ((global::Gtk.AttachOptions)(0));
		this.GtkAlignment3.Add (this.tblErrorTools1);
		this.frame3.Add (this.GtkAlignment3);
		this.GtkLabel6 = new global::Gtk.Label ();
		this.GtkLabel6.Name = "GtkLabel6";
		this.frame3.LabelWidget = this.GtkLabel6;
		this.alignment11.Add (this.frame3);
		this.expErrorToolsSetup.Add (this.alignment11);
		this.GtkLabel7 = new global::Gtk.Label ();
		this.GtkLabel7.Name = "GtkLabel7";
		this.GtkLabel7.Xpad = 5;
		this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Error Tools Setup</b>");
		this.GtkLabel7.UseMarkup = true;
		this.GtkLabel7.UseUnderline = true;
		this.GtkLabel7.SingleLineMode = true;
		this.expErrorToolsSetup.LabelWidget = this.GtkLabel7;
		this.alignment9.Add (this.expErrorToolsSetup);
		this.vbox3.Add (this.alignment9);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment9]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment5.Name = "alignment5";
		this.alignment5.LeftPadding = ((uint)(8));
		this.alignment5.TopPadding = ((uint)(8));
		this.alignment5.RightPadding = ((uint)(8));
		this.alignment5.BottomPadding = ((uint)(4));
		// Container child alignment5.Gtk.Container+ContainerChild
		this.tblErrorTools = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
		this.tblErrorTools.Name = "tblErrorTools";
		this.tblErrorTools.RowSpacing = ((uint)(6));
		this.tblErrorTools.ColumnSpacing = ((uint)(6));
		// Container child tblErrorTools.Gtk.Table+TableChild
		this.alignment13 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment13.Name = "alignment13";
		// Container child alignment13.Gtk.Container+ContainerChild
		this.btnErrorLogDisplay = new global::Gtk.Button ();
		this.btnErrorLogDisplay.CanFocus = true;
		this.btnErrorLogDisplay.Name = "btnErrorLogDisplay";
		this.btnErrorLogDisplay.UseUnderline = true;
		this.btnErrorLogDisplay.Label = global::Mono.Unix.Catalog.GetString ("Display Log Dialog...");
		this.alignment13.Add (this.btnErrorLogDisplay);
		this.tblErrorTools.Add (this.alignment13);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.tblErrorTools [this.alignment13]));
		w28.TopAttach = ((uint)(1));
		w28.BottomAttach = ((uint)(2));
		w28.LeftAttach = ((uint)(1));
		w28.RightAttach = ((uint)(2));
		w28.XOptions = ((global::Gtk.AttachOptions)(4));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblErrorTools.Gtk.Table+TableChild
		this.alignment6 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
		this.alignment6.Name = "alignment6";
		// Container child alignment6.Gtk.Container+ContainerChild
		this.lblDisplayErrorMessage = new global::Gtk.Label ();
		this.lblDisplayErrorMessage.Name = "lblDisplayErrorMessage";
		this.lblDisplayErrorMessage.LabelProp = global::Mono.Unix.Catalog.GetString ("Display Error Message:");
		this.lblDisplayErrorMessage.SingleLineMode = true;
		this.alignment6.Add (this.lblDisplayErrorMessage);
		this.tblErrorTools.Add (this.alignment6);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.tblErrorTools [this.alignment6]));
		w30.XOptions = ((global::Gtk.AttachOptions)(4));
		w30.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblErrorTools.Gtk.Table+TableChild
		this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment7.Name = "alignment7";
		// Container child alignment7.Gtk.Container+ContainerChild
		this.btnErrorDialogDisplay = new global::Gtk.Button ();
		this.btnErrorDialogDisplay.CanFocus = true;
		this.btnErrorDialogDisplay.Name = "btnErrorDialogDisplay";
		this.btnErrorDialogDisplay.UseUnderline = true;
		this.btnErrorDialogDisplay.Label = global::Mono.Unix.Catalog.GetString ("Display Error Dialog...");
		this.alignment7.Add (this.btnErrorDialogDisplay);
		this.tblErrorTools.Add (this.alignment7);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.tblErrorTools [this.alignment7]));
		w32.LeftAttach = ((uint)(1));
		w32.RightAttach = ((uint)(2));
		w32.XOptions = ((global::Gtk.AttachOptions)(4));
		w32.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblErrorTools.Gtk.Table+TableChild
		this.alignment8 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
		this.alignment8.Name = "alignment8";
		// Container child alignment8.Gtk.Container+ContainerChild
		this.lblDisplayErrorLog = new global::Gtk.Label ();
		this.lblDisplayErrorLog.Name = "lblDisplayErrorLog";
		this.lblDisplayErrorLog.LabelProp = global::Mono.Unix.Catalog.GetString ("Display Error Log:");
		this.lblDisplayErrorLog.SingleLineMode = true;
		this.alignment8.Add (this.lblDisplayErrorLog);
		this.tblErrorTools.Add (this.alignment8);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.tblErrorTools [this.alignment8]));
		w34.TopAttach = ((uint)(1));
		w34.BottomAttach = ((uint)(2));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblErrorTools.Gtk.Table+TableChild
		this.txtErrorMessage = new global::Gtk.Entry ();
		this.txtErrorMessage.CanFocus = true;
		this.txtErrorMessage.Name = "txtErrorMessage";
		this.txtErrorMessage.Text = global::Mono.Unix.Catalog.GetString ("This is a test error.");
		this.txtErrorMessage.IsEditable = true;
		this.tblErrorTools.Add (this.txtErrorMessage);
		global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.tblErrorTools [this.txtErrorMessage]));
		w35.LeftAttach = ((uint)(2));
		w35.RightAttach = ((uint)(4));
		w35.YOptions = ((global::Gtk.AttachOptions)(4));
		this.alignment5.Add (this.tblErrorTools);
		this.vbox3.Add (this.alignment5);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment5]));
		w37.Position = 1;
		this.nbkMain.Add (this.vbox3);
		// Notebook tab
		this.lblErrorTools = new global::Gtk.Label ();
		this.lblErrorTools.Name = "lblErrorTools";
		this.lblErrorTools.Xpad = 5;
		this.lblErrorTools.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Error Tools</b>");
		this.lblErrorTools.UseMarkup = true;
		this.lblErrorTools.SingleLineMode = true;
		this.nbkMain.SetTabLabel (this.vbox3, this.lblErrorTools);
		this.lblErrorTools.ShowAll ();
		// Notebook tab
		global::Gtk.Label w39 = new global::Gtk.Label ();
		w39.Visible = true;
		this.nbkMain.Add (w39);
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
		this.nbkMain.SetTabLabel (w39, this.label2);
		this.label2.ShowAll ();
		// Notebook tab
		global::Gtk.Label w40 = new global::Gtk.Label ();
		w40.Visible = true;
		this.nbkMain.Add (w40);
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("page3");
		this.nbkMain.SetTabLabel (w40, this.label3);
		this.label3.ShowAll ();
		// Notebook tab
		global::Gtk.Label w41 = new global::Gtk.Label ();
		w41.Visible = true;
		this.nbkMain.Add (w41);
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("page4");
		this.nbkMain.SetTabLabel (w41, this.label4);
		this.label4.ShowAll ();
		// Container child nbkMain.Gtk.Notebook+NotebookChild
		this.alignment10 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment10.Name = "alignment10";
		this.alignment10.LeftPadding = ((uint)(8));
		this.alignment10.TopPadding = ((uint)(8));
		this.nbkMain.Add (this.alignment10);
		global::Gtk.Notebook.NotebookChild w42 = ((global::Gtk.Notebook.NotebookChild)(this.nbkMain [this.alignment10]));
		w42.Position = 4;
		// Notebook tab
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("page5");
		this.nbkMain.SetTabLabel (this.alignment10, this.label5);
		this.label5.ShowAll ();
		this.alignment3.Add (this.nbkMain);
		this.vbox1.Add (this.alignment3);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment3]));
		w44.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment4.Name = "alignment4";
		// Container child alignment4.Gtk.Container+ContainerChild
		this.sbrMain = new global::Gtk.Statusbar ();
		this.sbrMain.Name = "sbrMain";
		this.sbrMain.Spacing = 6;
		this.alignment4.Add (this.sbrMain);
		this.vbox1.Add (this.alignment4);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment4]));
		w46.Position = 2;
		w46.Expand = false;
		w46.Fill = false;
		this.alignment1.Add (this.vbox1);
		this.Add (this.alignment1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 699;
		this.DefaultHeight = 519;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.tbrQuit.Activated += new global::System.EventHandler (this.OnTbrQuitActivated);
		this.tbrPreferences.Activated += new global::System.EventHandler (this.OnTbrPreferencesActivated);
		this.tbrHelp.Activated += new global::System.EventHandler (this.OnTbrHelpActivated);
		this.fcUserDataPath.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnFcUserDataPathExposeEvent);
		this.btnErrorDialogDisplay.Clicked += new global::System.EventHandler (this.OnBtnErrorDialogDisplayClicked);
		this.btnErrorLogDisplay.Clicked += new global::System.EventHandler (this.OnBtnErrorLogDisplayClicked);
	}
}
