#ifndef __BPMonitorGUIfrmPerson__
#define __BPMonitorGUIfrmPerson__

/**
@file
Subclass of frmPerson, which is generated by wxFormBuilder.
*/

#include "PBMonitorGUI.h"

/** Implementing frmPerson */
class BPMonitorGUIfrmPerson : public frmPerson
{
protected:
	// Handlers for frmPerson events.
	void btnAddEdit_OnClick( wxCommandEvent& event );
	void btnClose_Clicked( wxCommandEvent& event );
	
public:
	/** Constructor */
	BPMonitorGUIfrmPerson( wxWindow* parent );
};

#endif // __BPMonitorGUIfrmPerson__
