
// This file has been generated by the GUI designer. Do not modify.
namespace SQLiteMonoPlusUI {
    public partial class frmDatabaseConnect {
        private global::Gtk.Alignment alignment1;
        
        private global::Gtk.VBox vbox2;
        
        private global::Gtk.Alignment alignment2;
        
        private global::Gtk.Label lblTitle;
        
        private global::Gtk.Alignment alignment3;
        
        private global::Gtk.HSeparator hseparator1;
        
        private global::Gtk.Alignment alignment19;
        
        private global::Gtk.HBox hbox3;
        
        private global::Gtk.Alignment alignment20;
        
        private global::Gtk.RadioButton rbnNewConnection;
        
        private global::Gtk.Alignment alignment21;
        
        private global::Gtk.RadioButton rbnExistingConnection;
        
        private global::Gtk.Alignment alignment4;
        
        private global::Gtk.Table table1;
        
        private global::Gtk.Alignment alignment12;
        
        private global::Gtk.FileChooserButton fcDBFile;
        
        private global::Gtk.Alignment alignment13;
        
        private global::Gtk.Label label2;
        
        private global::Gtk.Alignment alignment14;
        
        private global::Gtk.Label label6;
        
        private global::Gtk.Alignment alignment15;
        
        private global::Gtk.Entry txtConnectionName;
        
        private global::Gtk.Alignment alignment6;
        
        private global::Gtk.Label label3;
        
        private global::Gtk.Alignment alignment8;
        
        private global::Gtk.Entry txtPassword;
        
        private global::Gtk.Alignment alignment5;
        
        private global::Gtk.HBox hbox1;
        
        private global::Gtk.Alignment alignment7;
        
        private global::Gtk.CheckButton cbxPooling;
        
        private global::Gtk.Alignment alignment9;
        
        private global::Gtk.Label lblMaxPool;
        
        private global::Gtk.Alignment alignment16;
        
        private global::Gtk.SpinButton spnMaxPool;
        
        private global::Gtk.Alignment alignment10;
        
        private global::Gtk.HSeparator hseparator2;
        
        private global::Gtk.Alignment alignment11;
        
        private global::Gtk.HBox hbox2;
        
        private global::Gtk.Alignment alignment17;
        
        private global::Gtk.Button btnTestConnection;
        
        private global::Gtk.Alignment alignment18;
        
        private global::Gtk.CheckButton cbxSaveConnection;
        
        private global::Gtk.Button btnCancel;
        
        private global::Gtk.Button btnConnect;
        
        protected virtual void Build() {
            global::Stetic.Gui.Initialize(this);
            // Widget SQLiteMonoPlusUI.frmDatabaseConnect
            this.Name = "SQLiteMonoPlusUI.frmDatabaseConnect";
            this.WindowPosition = ((global::Gtk.WindowPosition)(4));
            // Internal child SQLiteMonoPlusUI.frmDatabaseConnect.VBox
            global::Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.Spacing = 2;
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            // Container child alignment1.Gtk.Container+ContainerChild
            this.vbox2 = new global::Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment2.Name = "alignment2";
            this.alignment2.TopPadding = ((uint)(3));
            this.alignment2.BottomPadding = ((uint)(3));
            // Container child alignment2.Gtk.Container+ContainerChild
            this.lblTitle = new global::Gtk.Label();
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\"12000\"><b>Database Connection</b></span>");
            this.lblTitle.UseMarkup = true;
            this.lblTitle.Justify = ((global::Gtk.Justification)(2));
            this.alignment2.Add(this.lblTitle);
            this.vbox2.Add(this.alignment2);
            global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment2]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment3 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment3.Name = "alignment3";
            this.alignment3.BottomPadding = ((uint)(6));
            // Container child alignment3.Gtk.Container+ContainerChild
            this.hseparator1 = new global::Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.alignment3.Add(this.hseparator1);
            this.vbox2.Add(this.alignment3);
            global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment3]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment19 = new global::Gtk.Alignment(0.5F, 0.5F, 0.5F, 1F);
            this.alignment19.Name = "alignment19";
            // Container child alignment19.Gtk.Container+ContainerChild
            this.hbox3 = new global::Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.alignment20 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment20.Name = "alignment20";
            // Container child alignment20.Gtk.Container+ContainerChild
            this.rbnNewConnection = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("New Connection"));
            this.rbnNewConnection.CanFocus = true;
            this.rbnNewConnection.Name = "rbnNewConnection";
            this.rbnNewConnection.Active = true;
            this.rbnNewConnection.DrawIndicator = true;
            this.rbnNewConnection.UseUnderline = true;
            this.rbnNewConnection.Group = new global::GLib.SList(global::System.IntPtr.Zero);
            this.alignment20.Add(this.rbnNewConnection);
            this.hbox3.Add(this.alignment20);
            global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.alignment20]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.alignment21 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment21.Name = "alignment21";
            // Container child alignment21.Gtk.Container+ContainerChild
            this.rbnExistingConnection = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Existing Connection"));
            this.rbnExistingConnection.CanFocus = true;
            this.rbnExistingConnection.Name = "rbnExistingConnection";
            this.rbnExistingConnection.DrawIndicator = true;
            this.rbnExistingConnection.UseUnderline = true;
            this.rbnExistingConnection.Group = this.rbnNewConnection.Group;
            this.alignment21.Add(this.rbnExistingConnection);
            this.hbox3.Add(this.alignment21);
            global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.alignment21]));
            w9.Position = 1;
            w9.Expand = false;
            this.alignment19.Add(this.hbox3);
            this.vbox2.Add(this.alignment19);
            global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment19]));
            w11.Position = 2;
            w11.Expand = false;
            w11.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment4 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment4.Name = "alignment4";
            this.alignment4.LeftPadding = ((uint)(17));
            // Container child alignment4.Gtk.Container+ContainerChild
            this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(11));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.alignment12 = new global::Gtk.Alignment(0.01F, 0.5F, 0.01F, 1F);
            this.alignment12.Name = "alignment12";
            // Container child alignment12.Gtk.Container+ContainerChild
            this.fcDBFile = new global::Gtk.FileChooserButton(global::Mono.Unix.Catalog.GetString("Select A File"), ((global::Gtk.FileChooserAction)(0)));
            this.fcDBFile.WidthRequest = 350;
            this.fcDBFile.Name = "fcDBFile";
            this.alignment12.Add(this.fcDBFile);
            this.table1.Add(this.alignment12);
            global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.alignment12]));
            w13.TopAttach = ((uint)(1));
            w13.BottomAttach = ((uint)(2));
            w13.LeftAttach = ((uint)(1));
            w13.RightAttach = ((uint)(2));
            w13.YOptions = ((global::Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.alignment13 = new global::Gtk.Alignment(0.98F, 0.5F, 0.01F, 1F);
            this.alignment13.Name = "alignment13";
            // Container child alignment13.Gtk.Container+ContainerChild
            this.label2 = new global::Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("File:");
            this.alignment13.Add(this.label2);
            this.table1.Add(this.alignment13);
            global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.alignment13]));
            w15.TopAttach = ((uint)(1));
            w15.BottomAttach = ((uint)(2));
            w15.XOptions = ((global::Gtk.AttachOptions)(4));
            w15.YOptions = ((global::Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.alignment14 = new global::Gtk.Alignment(0.98F, 0.5F, 0.01F, 1F);
            this.alignment14.Name = "alignment14";
            // Container child alignment14.Gtk.Container+ContainerChild
            this.label6 = new global::Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Connection Name:");
            this.alignment14.Add(this.label6);
            this.table1.Add(this.alignment14);
            global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.alignment14]));
            w17.XOptions = ((global::Gtk.AttachOptions)(4));
            w17.YOptions = ((global::Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.alignment15 = new global::Gtk.Alignment(0.01F, 0.5F, 0.01F, 1F);
            this.alignment15.WidthRequest = 150;
            this.alignment15.Name = "alignment15";
            // Container child alignment15.Gtk.Container+ContainerChild
            this.txtConnectionName = new global::Gtk.Entry();
            this.txtConnectionName.WidthRequest = 200;
            this.txtConnectionName.CanFocus = true;
            this.txtConnectionName.Name = "txtConnectionName";
            this.txtConnectionName.IsEditable = true;
            this.txtConnectionName.InvisibleChar = '●';
            this.alignment15.Add(this.txtConnectionName);
            this.table1.Add(this.alignment15);
            global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.alignment15]));
            w19.LeftAttach = ((uint)(1));
            w19.RightAttach = ((uint)(2));
            w19.YOptions = ((global::Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.alignment6 = new global::Gtk.Alignment(0.98F, 0.5F, 0.01F, 1F);
            this.alignment6.Name = "alignment6";
            // Container child alignment6.Gtk.Container+ContainerChild
            this.label3 = new global::Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Password:");
            this.alignment6.Add(this.label3);
            this.table1.Add(this.alignment6);
            global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.alignment6]));
            w21.TopAttach = ((uint)(2));
            w21.BottomAttach = ((uint)(3));
            w21.XOptions = ((global::Gtk.AttachOptions)(4));
            w21.YOptions = ((global::Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.alignment8 = new global::Gtk.Alignment(0.01F, 0.5F, 0.01F, 1F);
            this.alignment8.Name = "alignment8";
            // Container child alignment8.Gtk.Container+ContainerChild
            this.txtPassword = new global::Gtk.Entry();
            this.txtPassword.WidthRequest = 200;
            this.txtPassword.CanFocus = true;
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.IsEditable = true;
            this.txtPassword.InvisibleChar = '●';
            this.alignment8.Add(this.txtPassword);
            this.table1.Add(this.alignment8);
            global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1[this.alignment8]));
            w23.TopAttach = ((uint)(2));
            w23.BottomAttach = ((uint)(3));
            w23.LeftAttach = ((uint)(1));
            w23.RightAttach = ((uint)(2));
            w23.YOptions = ((global::Gtk.AttachOptions)(4));
            this.alignment4.Add(this.table1);
            this.vbox2.Add(this.alignment4);
            global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment4]));
            w25.Position = 3;
            w25.Expand = false;
            w25.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment5 = new global::Gtk.Alignment(0.01F, 0.5F, 0.01F, 1F);
            this.alignment5.Name = "alignment5";
            this.alignment5.LeftPadding = ((uint)(110));
            this.alignment5.TopPadding = ((uint)(5));
            // Container child alignment5.Gtk.Container+ContainerChild
            this.hbox1 = new global::Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.alignment7 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment7.Name = "alignment7";
            this.alignment7.RightPadding = ((uint)(44));
            // Container child alignment7.Gtk.Container+ContainerChild
            this.cbxPooling = new global::Gtk.CheckButton();
            this.cbxPooling.CanFocus = true;
            this.cbxPooling.Name = "cbxPooling";
            this.cbxPooling.Label = global::Mono.Unix.Catalog.GetString("Connection Pooling");
            this.cbxPooling.DrawIndicator = true;
            this.cbxPooling.UseUnderline = true;
            this.alignment7.Add(this.cbxPooling);
            this.hbox1.Add(this.alignment7);
            global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment7]));
            w27.Position = 0;
            w27.Expand = false;
            w27.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.alignment9 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment9.Name = "alignment9";
            // Container child alignment9.Gtk.Container+ContainerChild
            this.lblMaxPool = new global::Gtk.Label();
            this.lblMaxPool.Name = "lblMaxPool";
            this.lblMaxPool.LabelProp = global::Mono.Unix.Catalog.GetString("Max Pool Connections:");
            this.alignment9.Add(this.lblMaxPool);
            this.hbox1.Add(this.alignment9);
            global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment9]));
            w29.Position = 1;
            w29.Expand = false;
            w29.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.alignment16 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment16.Name = "alignment16";
            // Container child alignment16.Gtk.Container+ContainerChild
            this.spnMaxPool = new global::Gtk.SpinButton(1D, 1000D, 1D);
            this.spnMaxPool.CanFocus = true;
            this.spnMaxPool.Name = "spnMaxPool";
            this.spnMaxPool.Adjustment.PageIncrement = 1D;
            this.spnMaxPool.ClimbRate = 1D;
            this.spnMaxPool.Numeric = true;
            this.spnMaxPool.SnapToTicks = true;
            this.spnMaxPool.UpdatePolicy = ((global::Gtk.SpinButtonUpdatePolicy)(1));
            this.spnMaxPool.Value = 100D;
            this.alignment16.Add(this.spnMaxPool);
            this.hbox1.Add(this.alignment16);
            global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment16]));
            w31.Position = 2;
            w31.Expand = false;
            w31.Fill = false;
            this.alignment5.Add(this.hbox1);
            this.vbox2.Add(this.alignment5);
            global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment5]));
            w33.Position = 4;
            w33.Expand = false;
            w33.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment10 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment10.Name = "alignment10";
            this.alignment10.TopPadding = ((uint)(3));
            this.alignment10.BottomPadding = ((uint)(3));
            // Container child alignment10.Gtk.Container+ContainerChild
            this.hseparator2 = new global::Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.alignment10.Add(this.hseparator2);
            this.vbox2.Add(this.alignment10);
            global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment10]));
            w35.Position = 5;
            w35.Expand = false;
            w35.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment11 = new global::Gtk.Alignment(0.5F, 0.5F, 0.01F, 1F);
            this.alignment11.Name = "alignment11";
            this.alignment11.TopPadding = ((uint)(8));
            this.alignment11.BottomPadding = ((uint)(7));
            // Container child alignment11.Gtk.Container+ContainerChild
            this.hbox2 = new global::Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 74;
            // Container child hbox2.Gtk.Box+BoxChild
            this.alignment17 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment17.Name = "alignment17";
            // Container child alignment17.Gtk.Container+ContainerChild
            this.btnTestConnection = new global::Gtk.Button();
            this.btnTestConnection.CanFocus = true;
            this.btnTestConnection.Name = "btnTestConnection";
            // Container child btnTestConnection.Gtk.Container+ContainerChild
            global::Gtk.Alignment w36 = new global::Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            global::Gtk.HBox w37 = new global::Gtk.HBox();
            w37.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            global::Gtk.Image w38 = new global::Gtk.Image();
            w38.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-connect", global::Gtk.IconSize.Button);
            w37.Add(w38);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            global::Gtk.Label w40 = new global::Gtk.Label();
            w40.LabelProp = global::Mono.Unix.Catalog.GetString("Test Connection");
            w37.Add(w40);
            w36.Add(w37);
            this.btnTestConnection.Add(w36);
            this.alignment17.Add(this.btnTestConnection);
            this.hbox2.Add(this.alignment17);
            global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.alignment17]));
            w45.Position = 0;
            w45.Expand = false;
            w45.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.alignment18 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment18.Name = "alignment18";
            // Container child alignment18.Gtk.Container+ContainerChild
            this.cbxSaveConnection = new global::Gtk.CheckButton();
            this.cbxSaveConnection.CanFocus = true;
            this.cbxSaveConnection.Name = "cbxSaveConnection";
            this.cbxSaveConnection.Label = global::Mono.Unix.Catalog.GetString("Register Connection");
            this.cbxSaveConnection.Active = true;
            this.cbxSaveConnection.DrawIndicator = true;
            this.cbxSaveConnection.UseUnderline = true;
            this.alignment18.Add(this.cbxSaveConnection);
            this.hbox2.Add(this.alignment18);
            global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.alignment18]));
            w47.Position = 1;
            w47.Expand = false;
            w47.Fill = false;
            this.alignment11.Add(this.hbox2);
            this.vbox2.Add(this.alignment11);
            global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.alignment11]));
            w49.Position = 6;
            w49.Expand = false;
            w49.Fill = false;
            this.alignment1.Add(this.vbox2);
            w1.Add(this.alignment1);
            global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(w1[this.alignment1]));
            w51.Position = 0;
            w51.Expand = false;
            w51.Fill = false;
            // Internal child SQLiteMonoPlusUI.frmDatabaseConnect.ActionArea
            global::Gtk.HButtonBox w52 = this.ActionArea;
            w52.Name = "dialog1_ActionArea";
            w52.Spacing = 10;
            w52.BorderWidth = ((uint)(7));
            w52.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.btnCancel = new global::Gtk.Button();
            this.btnCancel.CanDefault = true;
            this.btnCancel.CanFocus = true;
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.UseStock = true;
            this.btnCancel.UseUnderline = true;
            this.btnCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.btnCancel, -6);
            global::Gtk.ButtonBox.ButtonBoxChild w53 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w52[this.btnCancel]));
            w53.Expand = false;
            w53.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.btnConnect = new global::Gtk.Button();
            this.btnConnect.CanDefault = true;
            this.btnConnect.CanFocus = true;
            this.btnConnect.Name = "btnConnect";
            this.btnConnect.UseStock = true;
            this.btnConnect.UseUnderline = true;
            this.btnConnect.Label = "gtk-connect";
            this.AddActionWidget(this.btnConnect, -5);
            global::Gtk.ButtonBox.ButtonBoxChild w54 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w52[this.btnConnect]));
            w54.Position = 1;
            w54.Expand = false;
            w54.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 624;
            this.DefaultHeight = 319;
            this.lblMaxPool.Hide();
            this.spnMaxPool.Hide();
            this.Show();
            this.cbxPooling.Clicked += new global::System.EventHandler(this.cbxPooling_Clicked);
            this.btnTestConnection.Clicked += new global::System.EventHandler(this.btnTestConnection_Clicked);
            this.btnCancel.Clicked += new global::System.EventHandler(this.btnCancel_Clicked);
            this.btnConnect.Clicked += new global::System.EventHandler(this.btnConnect_Clicked);
        }
    }
}
