
// This file has been generated by the GUI designer. Do not modify.
namespace SQLiteMonoPlusUI
{
	public partial class frmPragmas
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.Table table1;
		private global::Gtk.Alignment alignment10;
		private global::Gtk.Label label1;
		private global::Gtk.Alignment alignment11;
		private global::Gtk.SpinButton spinbutton1;
		private global::Gtk.Alignment alignment12;
		private global::Gtk.Label label2;
		private global::Gtk.Alignment alignment13;
		private global::Gtk.SpinButton spinbutton2;
		private global::Gtk.Alignment alignment14;
		private global::Gtk.Label label3;
		private global::Gtk.Alignment alignment15;
		private global::Gtk.Label label4;
		private global::Gtk.Alignment alignment16;
		private global::Gtk.Label label5;
		private global::Gtk.Alignment alignment17;
		private global::Gtk.Label label6;
		private global::Gtk.Alignment alignment18;
		private global::Gtk.Label label7;
		private global::Gtk.Alignment alignment19;
		private global::Gtk.Label label8;
		private global::Gtk.Alignment alignment20;
		private global::Gtk.Label label9;
		private global::Gtk.Alignment alignment21;
		private global::Gtk.Label label10;
		private global::Gtk.Alignment alignment22;
		private global::Gtk.Label label11;
		private global::Gtk.Alignment alignment23;
		private global::Gtk.Label label12;
		private global::Gtk.Alignment alignment24;
		private global::Gtk.Label label13;
		private global::Gtk.Alignment alignment25;
		private global::Gtk.Label label14;
		private global::Gtk.Alignment alignment26;
		private global::Gtk.Label label15;
		private global::Gtk.Alignment alignment27;
		private global::Gtk.Label label16;
		private global::Gtk.Alignment alignment28;
		private global::Gtk.Label label17;
		private global::Gtk.Alignment alignment29;
		private global::Gtk.Label label18;
		private global::Gtk.Alignment alignment30;
		private global::Gtk.Label label19;
		private global::Gtk.Alignment alignment31;
		private global::Gtk.Label label20;
		private global::Gtk.Alignment alignment32;
		private global::Gtk.Label label21;
		private global::Gtk.Alignment alignment33;
		private global::Gtk.SpinButton spnUserVersion;
		private global::Gtk.Alignment alignment34;
		private global::Gtk.SpinButton spnSchemaVersion;
		private global::Gtk.Alignment alignment35;
		private global::Gtk.SpinButton spnPageSize;
		private global::Gtk.Alignment alignment36;
		private global::Gtk.SpinButton spnMaxPageCount;
		private global::Gtk.Alignment alignment38;
		private global::Gtk.CheckButton cbxAutoIndex;
		private global::Gtk.Alignment alignment39;
		private global::Gtk.CheckButton cbxForeignKeys;
		private global::Gtk.Alignment alignment40;
		private global::Gtk.CheckButton cbxIgnorCheckConstraints;
		private global::Gtk.Alignment alignment41;
		private global::Gtk.CheckButton cbxReadUncommitted;
		private global::Gtk.Alignment alignment42;
		private global::Gtk.CheckButton cbxRecursiveTriggers;
		private global::Gtk.Alignment alignment43;
		private global::Gtk.CheckButton cbxReverseUnorderedSelects;
		private global::Gtk.Alignment alignment44;
		private global::Gtk.CheckButton cbxWritableSchema;
		private global::Gtk.Alignment alignment45;
		private global::Gtk.CheckButton cbxSecureDelete;
		private global::Gtk.Alignment alignment46;
		private global::Gtk.CheckButton cbxCaseSensitiveLike;
		private global::Gtk.Alignment alignment47;
		private global::Gtk.ComboBox cboAutoVacuum;
		private global::Gtk.Alignment alignment48;
		private global::Gtk.ComboBox cboJournalMode;
		private global::Gtk.Alignment alignment49;
		private global::Gtk.ComboBox cboLockingMode;
		private global::Gtk.Alignment alignment50;
		private global::Gtk.ComboBox cboSynchronous;
		private global::Gtk.Alignment alignment51;
		private global::Gtk.ComboBox cboTempStore;
		private global::Gtk.Alignment alignment52;
		private global::Gtk.ComboBox cboEncoding;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button button17;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SQLiteMonoPlusUI.frmPragmas
			this.Name = "SQLiteMonoPlusUI.frmPragmas";
			this.Title = global::Mono.Unix.Catalog.GetString ("PRAGMA Properties");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(5));
			// Internal child SQLiteMonoPlusUI.frmPragmas.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w2 = new global::Gtk.Viewport ();
			w2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(50));
			this.GtkAlignment2.TopPadding = ((uint)(8));
			this.GtkAlignment2.BottomPadding = ((uint)(3));
			this.GtkAlignment2.BorderWidth = ((uint)(3));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(21)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.alignment10 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment10.Name = "alignment10";
			// Container child alignment10.Gtk.Container+ContainerChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Auto Vacuum:");
			this.alignment10.Add (this.label1);
			this.table1.Add (this.alignment10);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment10]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment11 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment11.Name = "alignment11";
			// Container child alignment11.Gtk.Container+ContainerChild
			this.spinbutton1 = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.spinbutton1.CanFocus = true;
			this.spinbutton1.Name = "spinbutton1";
			this.spinbutton1.Adjustment.PageIncrement = 10D;
			this.spinbutton1.ClimbRate = 1D;
			this.spinbutton1.Numeric = true;
			this.alignment11.Add (this.spinbutton1);
			this.table1.Add (this.alignment11);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment11]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment12 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment12.Name = "alignment12";
			// Container child alignment12.Gtk.Container+ContainerChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Auto Index:");
			this.alignment12.Add (this.label2);
			this.table1.Add (this.alignment12);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment12]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment13 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment13.Name = "alignment13";
			// Container child alignment13.Gtk.Container+ContainerChild
			this.spinbutton2 = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.spinbutton2.CanFocus = true;
			this.spinbutton2.Name = "spinbutton2";
			this.spinbutton2.Adjustment.PageIncrement = 10D;
			this.spinbutton2.ClimbRate = 1D;
			this.spinbutton2.Numeric = true;
			this.alignment13.Add (this.spinbutton2);
			this.table1.Add (this.alignment13);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment13]));
			w10.TopAttach = ((uint)(8));
			w10.BottomAttach = ((uint)(9));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment14 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment14.Name = "alignment14";
			// Container child alignment14.Gtk.Container+ContainerChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Cache Size:");
			this.alignment14.Add (this.label3);
			this.table1.Add (this.alignment14);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment14]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment15 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment15.Name = "alignment15";
			// Container child alignment15.Gtk.Container+ContainerChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Case Sensitive Like:");
			this.alignment15.Add (this.label4);
			this.table1.Add (this.alignment15);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment15]));
			w14.TopAttach = ((uint)(3));
			w14.BottomAttach = ((uint)(4));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment16 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment16.Name = "alignment16";
			// Container child alignment16.Gtk.Container+ContainerChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Encoding:");
			this.alignment16.Add (this.label5);
			this.table1.Add (this.alignment16);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment16]));
			w16.TopAttach = ((uint)(4));
			w16.BottomAttach = ((uint)(5));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment17 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment17.Name = "alignment17";
			// Container child alignment17.Gtk.Container+ContainerChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Foreign Keys:");
			this.alignment17.Add (this.label6);
			this.table1.Add (this.alignment17);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment17]));
			w18.TopAttach = ((uint)(5));
			w18.BottomAttach = ((uint)(6));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment18 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment18.Name = "alignment18";
			// Container child alignment18.Gtk.Container+ContainerChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Ignore Check Constraints:");
			this.alignment18.Add (this.label7);
			this.table1.Add (this.alignment18);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment18]));
			w20.TopAttach = ((uint)(6));
			w20.BottomAttach = ((uint)(7));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment19 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment19.Name = "alignment19";
			// Container child alignment19.Gtk.Container+ContainerChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Journal Mode:");
			this.alignment19.Add (this.label8);
			this.table1.Add (this.alignment19);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment19]));
			w22.TopAttach = ((uint)(7));
			w22.BottomAttach = ((uint)(8));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment20 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment20.Name = "alignment20";
			// Container child alignment20.Gtk.Container+ContainerChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Journal Size Limit:");
			this.alignment20.Add (this.label9);
			this.table1.Add (this.alignment20);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment20]));
			w24.TopAttach = ((uint)(8));
			w24.BottomAttach = ((uint)(9));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment21 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment21.Name = "alignment21";
			// Container child alignment21.Gtk.Container+ContainerChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Locking Mode:");
			this.alignment21.Add (this.label10);
			this.table1.Add (this.alignment21);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment21]));
			w26.TopAttach = ((uint)(9));
			w26.BottomAttach = ((uint)(10));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment22 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment22.Name = "alignment22";
			// Container child alignment22.Gtk.Container+ContainerChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Max Page Count:");
			this.alignment22.Add (this.label11);
			this.table1.Add (this.alignment22);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment22]));
			w28.TopAttach = ((uint)(10));
			w28.BottomAttach = ((uint)(11));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment23 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment23.Name = "alignment23";
			// Container child alignment23.Gtk.Container+ContainerChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Page Size:");
			this.alignment23.Add (this.label12);
			this.table1.Add (this.alignment23);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment23]));
			w30.TopAttach = ((uint)(11));
			w30.BottomAttach = ((uint)(12));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment24 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment24.Name = "alignment24";
			// Container child alignment24.Gtk.Container+ContainerChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Read Uncommitted:");
			this.alignment24.Add (this.label13);
			this.table1.Add (this.alignment24);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment24]));
			w32.TopAttach = ((uint)(12));
			w32.BottomAttach = ((uint)(13));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment25 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment25.Name = "alignment25";
			// Container child alignment25.Gtk.Container+ContainerChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Recursive Triggers:");
			this.alignment25.Add (this.label14);
			this.table1.Add (this.alignment25);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment25]));
			w34.TopAttach = ((uint)(13));
			w34.BottomAttach = ((uint)(14));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment26 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment26.Name = "alignment26";
			// Container child alignment26.Gtk.Container+ContainerChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Reverse Unordered Selects:");
			this.alignment26.Add (this.label15);
			this.table1.Add (this.alignment26);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment26]));
			w36.TopAttach = ((uint)(14));
			w36.BottomAttach = ((uint)(15));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment27 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment27.Name = "alignment27";
			// Container child alignment27.Gtk.Container+ContainerChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Schema Version:");
			this.alignment27.Add (this.label16);
			this.table1.Add (this.alignment27);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment27]));
			w38.TopAttach = ((uint)(15));
			w38.BottomAttach = ((uint)(16));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment28 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment28.Name = "alignment28";
			// Container child alignment28.Gtk.Container+ContainerChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Secure Delete:");
			this.alignment28.Add (this.label17);
			this.table1.Add (this.alignment28);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment28]));
			w40.TopAttach = ((uint)(16));
			w40.BottomAttach = ((uint)(17));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment29 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment29.Name = "alignment29";
			// Container child alignment29.Gtk.Container+ContainerChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Synchronous:");
			this.alignment29.Add (this.label18);
			this.table1.Add (this.alignment29);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment29]));
			w42.TopAttach = ((uint)(17));
			w42.BottomAttach = ((uint)(18));
			w42.XOptions = ((global::Gtk.AttachOptions)(4));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment30 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment30.Name = "alignment30";
			// Container child alignment30.Gtk.Container+ContainerChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Temp Store:");
			this.alignment30.Add (this.label19);
			this.table1.Add (this.alignment30);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment30]));
			w44.TopAttach = ((uint)(18));
			w44.BottomAttach = ((uint)(19));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment31 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment31.Name = "alignment31";
			// Container child alignment31.Gtk.Container+ContainerChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("User Version:");
			this.alignment31.Add (this.label20);
			this.table1.Add (this.alignment31);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment31]));
			w46.TopAttach = ((uint)(19));
			w46.BottomAttach = ((uint)(20));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment32 = new global::Gtk.Alignment (0.98F, 0.5F, 0.01F, 1F);
			this.alignment32.Name = "alignment32";
			// Container child alignment32.Gtk.Container+ContainerChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Writable Schema:");
			this.alignment32.Add (this.label21);
			this.table1.Add (this.alignment32);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment32]));
			w48.TopAttach = ((uint)(20));
			w48.BottomAttach = ((uint)(21));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment33 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment33.Name = "alignment33";
			// Container child alignment33.Gtk.Container+ContainerChild
			this.spnUserVersion = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.spnUserVersion.CanFocus = true;
			this.spnUserVersion.Name = "spnUserVersion";
			this.spnUserVersion.Adjustment.PageIncrement = 10D;
			this.spnUserVersion.ClimbRate = 1D;
			this.spnUserVersion.Numeric = true;
			this.alignment33.Add (this.spnUserVersion);
			this.table1.Add (this.alignment33);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment33]));
			w50.TopAttach = ((uint)(19));
			w50.BottomAttach = ((uint)(20));
			w50.LeftAttach = ((uint)(1));
			w50.RightAttach = ((uint)(2));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment34 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment34.Name = "alignment34";
			// Container child alignment34.Gtk.Container+ContainerChild
			this.spnSchemaVersion = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.spnSchemaVersion.CanFocus = true;
			this.spnSchemaVersion.Name = "spnSchemaVersion";
			this.spnSchemaVersion.Adjustment.PageIncrement = 10D;
			this.spnSchemaVersion.ClimbRate = 1D;
			this.spnSchemaVersion.Numeric = true;
			this.alignment34.Add (this.spnSchemaVersion);
			this.table1.Add (this.alignment34);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment34]));
			w52.TopAttach = ((uint)(15));
			w52.BottomAttach = ((uint)(16));
			w52.LeftAttach = ((uint)(1));
			w52.RightAttach = ((uint)(2));
			w52.XOptions = ((global::Gtk.AttachOptions)(4));
			w52.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment35 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment35.Name = "alignment35";
			// Container child alignment35.Gtk.Container+ContainerChild
			this.spnPageSize = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.spnPageSize.CanFocus = true;
			this.spnPageSize.Name = "spnPageSize";
			this.spnPageSize.Adjustment.PageIncrement = 10D;
			this.spnPageSize.ClimbRate = 1D;
			this.spnPageSize.Numeric = true;
			this.alignment35.Add (this.spnPageSize);
			this.table1.Add (this.alignment35);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment35]));
			w54.TopAttach = ((uint)(11));
			w54.BottomAttach = ((uint)(12));
			w54.LeftAttach = ((uint)(1));
			w54.RightAttach = ((uint)(2));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment36 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment36.Name = "alignment36";
			// Container child alignment36.Gtk.Container+ContainerChild
			this.spnMaxPageCount = new global::Gtk.SpinButton (0D, 100D, 1D);
			this.spnMaxPageCount.CanFocus = true;
			this.spnMaxPageCount.Name = "spnMaxPageCount";
			this.spnMaxPageCount.Adjustment.PageIncrement = 10D;
			this.spnMaxPageCount.ClimbRate = 1D;
			this.spnMaxPageCount.Numeric = true;
			this.alignment36.Add (this.spnMaxPageCount);
			this.table1.Add (this.alignment36);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment36]));
			w56.TopAttach = ((uint)(10));
			w56.BottomAttach = ((uint)(11));
			w56.LeftAttach = ((uint)(1));
			w56.RightAttach = ((uint)(2));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment38 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment38.Name = "alignment38";
			// Container child alignment38.Gtk.Container+ContainerChild
			this.cbxAutoIndex = new global::Gtk.CheckButton ();
			this.cbxAutoIndex.CanFocus = true;
			this.cbxAutoIndex.Name = "cbxAutoIndex";
			this.cbxAutoIndex.Label = "";
			this.cbxAutoIndex.DrawIndicator = true;
			this.cbxAutoIndex.UseUnderline = true;
			this.alignment38.Add (this.cbxAutoIndex);
			this.table1.Add (this.alignment38);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment38]));
			w58.TopAttach = ((uint)(1));
			w58.BottomAttach = ((uint)(2));
			w58.LeftAttach = ((uint)(1));
			w58.RightAttach = ((uint)(2));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment39 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment39.Name = "alignment39";
			// Container child alignment39.Gtk.Container+ContainerChild
			this.cbxForeignKeys = new global::Gtk.CheckButton ();
			this.cbxForeignKeys.CanFocus = true;
			this.cbxForeignKeys.Name = "cbxForeignKeys";
			this.cbxForeignKeys.Label = "";
			this.cbxForeignKeys.DrawIndicator = true;
			this.cbxForeignKeys.UseUnderline = true;
			this.alignment39.Add (this.cbxForeignKeys);
			this.table1.Add (this.alignment39);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment39]));
			w60.TopAttach = ((uint)(5));
			w60.BottomAttach = ((uint)(6));
			w60.LeftAttach = ((uint)(1));
			w60.RightAttach = ((uint)(2));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment40 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment40.Name = "alignment40";
			// Container child alignment40.Gtk.Container+ContainerChild
			this.cbxIgnorCheckConstraints = new global::Gtk.CheckButton ();
			this.cbxIgnorCheckConstraints.CanFocus = true;
			this.cbxIgnorCheckConstraints.Name = "cbxIgnorCheckConstraints";
			this.cbxIgnorCheckConstraints.Label = "";
			this.cbxIgnorCheckConstraints.DrawIndicator = true;
			this.cbxIgnorCheckConstraints.UseUnderline = true;
			this.alignment40.Add (this.cbxIgnorCheckConstraints);
			this.table1.Add (this.alignment40);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment40]));
			w62.TopAttach = ((uint)(6));
			w62.BottomAttach = ((uint)(7));
			w62.LeftAttach = ((uint)(1));
			w62.RightAttach = ((uint)(2));
			w62.XOptions = ((global::Gtk.AttachOptions)(4));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment41 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment41.Name = "alignment41";
			// Container child alignment41.Gtk.Container+ContainerChild
			this.cbxReadUncommitted = new global::Gtk.CheckButton ();
			this.cbxReadUncommitted.CanFocus = true;
			this.cbxReadUncommitted.Name = "cbxReadUncommitted";
			this.cbxReadUncommitted.Label = "";
			this.cbxReadUncommitted.DrawIndicator = true;
			this.cbxReadUncommitted.UseUnderline = true;
			this.alignment41.Add (this.cbxReadUncommitted);
			this.table1.Add (this.alignment41);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment41]));
			w64.TopAttach = ((uint)(12));
			w64.BottomAttach = ((uint)(13));
			w64.LeftAttach = ((uint)(1));
			w64.RightAttach = ((uint)(2));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment42 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment42.Name = "alignment42";
			// Container child alignment42.Gtk.Container+ContainerChild
			this.cbxRecursiveTriggers = new global::Gtk.CheckButton ();
			this.cbxRecursiveTriggers.CanFocus = true;
			this.cbxRecursiveTriggers.Name = "cbxRecursiveTriggers";
			this.cbxRecursiveTriggers.Label = "";
			this.cbxRecursiveTriggers.DrawIndicator = true;
			this.cbxRecursiveTriggers.UseUnderline = true;
			this.alignment42.Add (this.cbxRecursiveTriggers);
			this.table1.Add (this.alignment42);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment42]));
			w66.TopAttach = ((uint)(13));
			w66.BottomAttach = ((uint)(14));
			w66.LeftAttach = ((uint)(1));
			w66.RightAttach = ((uint)(2));
			w66.XOptions = ((global::Gtk.AttachOptions)(4));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment43 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment43.Name = "alignment43";
			// Container child alignment43.Gtk.Container+ContainerChild
			this.cbxReverseUnorderedSelects = new global::Gtk.CheckButton ();
			this.cbxReverseUnorderedSelects.CanFocus = true;
			this.cbxReverseUnorderedSelects.Name = "cbxReverseUnorderedSelects";
			this.cbxReverseUnorderedSelects.Label = "";
			this.cbxReverseUnorderedSelects.DrawIndicator = true;
			this.cbxReverseUnorderedSelects.UseUnderline = true;
			this.alignment43.Add (this.cbxReverseUnorderedSelects);
			this.table1.Add (this.alignment43);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment43]));
			w68.TopAttach = ((uint)(14));
			w68.BottomAttach = ((uint)(15));
			w68.LeftAttach = ((uint)(1));
			w68.RightAttach = ((uint)(2));
			w68.XOptions = ((global::Gtk.AttachOptions)(4));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment44 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment44.Name = "alignment44";
			// Container child alignment44.Gtk.Container+ContainerChild
			this.cbxWritableSchema = new global::Gtk.CheckButton ();
			this.cbxWritableSchema.CanFocus = true;
			this.cbxWritableSchema.Name = "cbxWritableSchema";
			this.cbxWritableSchema.Label = "";
			this.cbxWritableSchema.DrawIndicator = true;
			this.cbxWritableSchema.UseUnderline = true;
			this.alignment44.Add (this.cbxWritableSchema);
			this.table1.Add (this.alignment44);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment44]));
			w70.TopAttach = ((uint)(20));
			w70.BottomAttach = ((uint)(21));
			w70.LeftAttach = ((uint)(1));
			w70.RightAttach = ((uint)(2));
			w70.XOptions = ((global::Gtk.AttachOptions)(4));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment45 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment45.Name = "alignment45";
			// Container child alignment45.Gtk.Container+ContainerChild
			this.cbxSecureDelete = new global::Gtk.CheckButton ();
			this.cbxSecureDelete.CanFocus = true;
			this.cbxSecureDelete.Name = "cbxSecureDelete";
			this.cbxSecureDelete.Label = "";
			this.cbxSecureDelete.DrawIndicator = true;
			this.cbxSecureDelete.UseUnderline = true;
			this.alignment45.Add (this.cbxSecureDelete);
			this.table1.Add (this.alignment45);
			global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment45]));
			w72.TopAttach = ((uint)(16));
			w72.BottomAttach = ((uint)(17));
			w72.LeftAttach = ((uint)(1));
			w72.RightAttach = ((uint)(2));
			w72.XOptions = ((global::Gtk.AttachOptions)(4));
			w72.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment46 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment46.Name = "alignment46";
			// Container child alignment46.Gtk.Container+ContainerChild
			this.cbxCaseSensitiveLike = new global::Gtk.CheckButton ();
			this.cbxCaseSensitiveLike.CanFocus = true;
			this.cbxCaseSensitiveLike.Name = "cbxCaseSensitiveLike";
			this.cbxCaseSensitiveLike.Label = "";
			this.cbxCaseSensitiveLike.DrawIndicator = true;
			this.cbxCaseSensitiveLike.UseUnderline = true;
			this.alignment46.Add (this.cbxCaseSensitiveLike);
			this.table1.Add (this.alignment46);
			global::Gtk.Table.TableChild w74 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment46]));
			w74.TopAttach = ((uint)(3));
			w74.BottomAttach = ((uint)(4));
			w74.LeftAttach = ((uint)(1));
			w74.RightAttach = ((uint)(2));
			w74.XOptions = ((global::Gtk.AttachOptions)(4));
			w74.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment47 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment47.Name = "alignment47";
			// Container child alignment47.Gtk.Container+ContainerChild
			this.cboAutoVacuum = global::Gtk.ComboBox.NewText ();
			this.cboAutoVacuum.AppendText (global::Mono.Unix.Catalog.GetString ("None"));
			this.cboAutoVacuum.AppendText (global::Mono.Unix.Catalog.GetString ("Full"));
			this.cboAutoVacuum.AppendText (global::Mono.Unix.Catalog.GetString ("Incremental"));
			this.cboAutoVacuum.Name = "cboAutoVacuum";
			this.cboAutoVacuum.Active = 0;
			this.alignment47.Add (this.cboAutoVacuum);
			this.table1.Add (this.alignment47);
			global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment47]));
			w76.LeftAttach = ((uint)(1));
			w76.RightAttach = ((uint)(2));
			w76.XOptions = ((global::Gtk.AttachOptions)(4));
			w76.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment48 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment48.Name = "alignment48";
			// Container child alignment48.Gtk.Container+ContainerChild
			this.cboJournalMode = global::Gtk.ComboBox.NewText ();
			this.cboJournalMode.AppendText (global::Mono.Unix.Catalog.GetString ("Delete"));
			this.cboJournalMode.AppendText (global::Mono.Unix.Catalog.GetString ("Truncate"));
			this.cboJournalMode.AppendText (global::Mono.Unix.Catalog.GetString ("Persist"));
			this.cboJournalMode.AppendText (global::Mono.Unix.Catalog.GetString ("Memory"));
			this.cboJournalMode.AppendText (global::Mono.Unix.Catalog.GetString ("Wal"));
			this.cboJournalMode.AppendText (global::Mono.Unix.Catalog.GetString ("Off "));
			this.cboJournalMode.Name = "cboJournalMode";
			this.cboJournalMode.Active = 0;
			this.alignment48.Add (this.cboJournalMode);
			this.table1.Add (this.alignment48);
			global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment48]));
			w78.TopAttach = ((uint)(7));
			w78.BottomAttach = ((uint)(8));
			w78.LeftAttach = ((uint)(1));
			w78.RightAttach = ((uint)(2));
			w78.XOptions = ((global::Gtk.AttachOptions)(4));
			w78.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment49 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment49.Name = "alignment49";
			// Container child alignment49.Gtk.Container+ContainerChild
			this.cboLockingMode = global::Gtk.ComboBox.NewText ();
			this.cboLockingMode.AppendText (global::Mono.Unix.Catalog.GetString ("Normal"));
			this.cboLockingMode.AppendText (global::Mono.Unix.Catalog.GetString ("Exclusive"));
			this.cboLockingMode.Name = "cboLockingMode";
			this.cboLockingMode.Active = 0;
			this.alignment49.Add (this.cboLockingMode);
			this.table1.Add (this.alignment49);
			global::Gtk.Table.TableChild w80 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment49]));
			w80.TopAttach = ((uint)(9));
			w80.BottomAttach = ((uint)(10));
			w80.LeftAttach = ((uint)(1));
			w80.RightAttach = ((uint)(2));
			w80.XOptions = ((global::Gtk.AttachOptions)(4));
			w80.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment50 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment50.Name = "alignment50";
			// Container child alignment50.Gtk.Container+ContainerChild
			this.cboSynchronous = global::Gtk.ComboBox.NewText ();
			this.cboSynchronous.AppendText (global::Mono.Unix.Catalog.GetString ("Off"));
			this.cboSynchronous.AppendText (global::Mono.Unix.Catalog.GetString ("Normal"));
			this.cboSynchronous.AppendText (global::Mono.Unix.Catalog.GetString ("Full"));
			this.cboSynchronous.Name = "cboSynchronous";
			this.cboSynchronous.Active = 1;
			this.alignment50.Add (this.cboSynchronous);
			this.table1.Add (this.alignment50);
			global::Gtk.Table.TableChild w82 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment50]));
			w82.TopAttach = ((uint)(17));
			w82.BottomAttach = ((uint)(18));
			w82.LeftAttach = ((uint)(1));
			w82.RightAttach = ((uint)(2));
			w82.XOptions = ((global::Gtk.AttachOptions)(4));
			w82.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment51 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment51.Name = "alignment51";
			// Container child alignment51.Gtk.Container+ContainerChild
			this.cboTempStore = global::Gtk.ComboBox.NewText ();
			this.cboTempStore.AppendText (global::Mono.Unix.Catalog.GetString ("Default"));
			this.cboTempStore.AppendText (global::Mono.Unix.Catalog.GetString ("File"));
			this.cboTempStore.AppendText (global::Mono.Unix.Catalog.GetString ("Memory"));
			this.cboTempStore.Name = "cboTempStore";
			this.cboTempStore.Active = 0;
			this.alignment51.Add (this.cboTempStore);
			this.table1.Add (this.alignment51);
			global::Gtk.Table.TableChild w84 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment51]));
			w84.TopAttach = ((uint)(18));
			w84.BottomAttach = ((uint)(19));
			w84.LeftAttach = ((uint)(1));
			w84.RightAttach = ((uint)(2));
			w84.XOptions = ((global::Gtk.AttachOptions)(4));
			w84.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.alignment52 = new global::Gtk.Alignment (0.02F, 0.5F, 0.01F, 1F);
			this.alignment52.Name = "alignment52";
			// Container child alignment52.Gtk.Container+ContainerChild
			this.cboEncoding = global::Gtk.ComboBox.NewText ();
			this.cboEncoding.AppendText (global::Mono.Unix.Catalog.GetString ("UTF-8"));
			this.cboEncoding.AppendText (global::Mono.Unix.Catalog.GetString ("UTF-16"));
			this.cboEncoding.AppendText (global::Mono.Unix.Catalog.GetString ("UTF-16le"));
			this.cboEncoding.AppendText (global::Mono.Unix.Catalog.GetString ("UTF-16be"));
			this.cboEncoding.Name = "cboEncoding";
			this.cboEncoding.Active = 0;
			this.alignment52.Add (this.cboEncoding);
			this.table1.Add (this.alignment52);
			global::Gtk.Table.TableChild w86 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment52]));
			w86.TopAttach = ((uint)(4));
			w86.BottomAttach = ((uint)(5));
			w86.LeftAttach = ((uint)(1));
			w86.RightAttach = ((uint)(2));
			w86.XOptions = ((global::Gtk.AttachOptions)(4));
			w86.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add (this.table1);
			w2.Add (this.GtkAlignment2);
			this.scrolledwindow1.Add (w2);
			w1.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(w1 [this.scrolledwindow1]));
			w90.Position = 0;
			// Internal child SQLiteMonoPlusUI.frmPragmas.ActionArea
			global::Gtk.HButtonBox w91 = this.ActionArea;
			w91.Name = "dialog1_ActionArea";
			w91.Spacing = 10;
			w91.BorderWidth = ((uint)(5));
			w91.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w92 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w91 [this.buttonCancel]));
			w92.Expand = false;
			w92.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button17 = new global::Gtk.Button ();
			this.button17.CanFocus = true;
			this.button17.Name = "button17";
			this.button17.UseStock = true;
			this.button17.UseUnderline = true;
			this.button17.Label = "gtk-save";
			this.AddActionWidget (this.button17, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w93 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w91 [this.button17]));
			w93.Position = 1;
			w93.Expand = false;
			w93.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 631;
			this.DefaultHeight = 583;
			this.Show ();
		}
	}
}
