#ifndef __frmPerson__
#define __frmPerson__

/**
@file
Subclass of frmPersonGUI, which is generated by wxFormBuilder.
*/

#include "wxBPMonitor.h"

/** Implementing frmPersonGUI */
class frmPerson : public frmPersonGUI
{
protected:
	// Handlers for frmPersonGUI events.
	void btnAddEdit_OnClick( wxCommandEvent& event );
	void btnClose_Clicked( wxCommandEvent& event );
	
public:
	/** Constructor */
	frmPerson( wxWindow* parent );
};

#endif // __frmPerson__
