// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GUPdotNET {
    
    
    public partial class frmInstall {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.Label lblTitle;
        
        private Gtk.Alignment alignment2;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Alignment alignment3;
        
        private Gtk.Label lblMessage;
        
        private Gtk.Expander expander1;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment2;
        
        private Gtk.Alignment alignment4;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TextView textview1;
        
        private Gtk.Label GtkLabel3;
        
        private Gtk.Alignment alignment5;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.Button buttonOk;
    }
}
