
// This file has been generated by the GUI designer. Do not modify.
namespace SQLiteMonoPlusEditor
{
	public partial class SQLTextEditor
	{
		private global::Gtk.Alignment alignment1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::SQLiteMonoPlusEditor.SQLEditor.SQLEditorView sqleditorview4;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SQLiteMonoPlusEditor.SQLTextEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "SQLiteMonoPlusEditor.SQLTextEditor";
			// Container child SQLiteMonoPlusEditor.SQLTextEditor.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.sqleditorview4 = null;
			this.GtkScrolledWindow.Add (this.sqleditorview4);
			this.alignment1.Add (this.GtkScrolledWindow);
			this.Add (this.alignment1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
