#ifndef __wxBPMonitorGUIfrmEntry__
#define __wxBPMonitorGUIfrmEntry__

/**
@file
Subclass of frmEntry, which is generated by wxFormBuilder.
*/

#include "wxBPMonitor.h"

/** Implementing frmEntry */
class wxBPMonitorGUIfrmEntry : public frmEntry
{
protected:
	// Handlers for frmEntry events.
	void btnCancel_Clicked( wxCommandEvent& event );
	void btnOk_Clicked( wxCommandEvent& event );
	
public:
	/** Constructor */
	wxBPMonitorGUIfrmEntry( wxWindow* parent );
};

#endif // __wxBPMonitorGUIfrmEntry__
