//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace MonoBPMonitor
{


	public partial class frmErrorMessage : Gtk.Dialog
	{
		protected virtual void OnBtnProjectSiteClicked (object sender, System.EventArgs e)
		{
		}
		
		

		public frmErrorMessage ()
		{
			this.Build ();
		}
	}
}
