//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace CMYControls
{


	[System.ComponentModel.ToolboxItem(true)]
	public partial class QuickDate : Gtk.Bin
	{
		protected virtual void OnBtnClearCalendarRealized (object sender, System.EventArgs e)
		{
			btnClearCalendar.HeightRequest = txtDate.Allocation.Height - 2;
		}
		
		
		public QuickDate ()
		{
			this.Build ();
			this.ShowAll();
		}
		protected virtual void OnImgClearCalendarRealized (object sender, System.EventArgs e)
		{
			imgClearCalendar.HeightRequest = txtDate.Allocation.Height - 4;
		}
		
		
	}
}
