//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Gtk;


namespace CMYControls
{


	[System.ComponentModel.ToolboxItem(true)]
	public partial class QuickDate : Gtk.Bin
	{
		public QuickDate ()
		{
			this.AppPaintable = true;
			this.Build ();
		}
		
		protected virtual void OnBtnShowCalendarClicked (object sender, System.EventArgs e)
		{
		}
		
		protected virtual void OnBtnClearCalendarClicked (object sender, System.EventArgs e)
		{
		}
		
	}
}
