// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GUPdotNET {
    
    
    public partial class frmUpdateConfirm {
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.Label label1;
        
        private Gtk.Alignment alignment10;
        
        private Gtk.Button btnAbout;
        
        private Gtk.Label label4;
        
        private Gtk.Alignment alignment2;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Alignment alignment3;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment2;
        
        private Gtk.Alignment alignment4;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Alignment alignment8;
        
        private Gtk.Label label2;
        
        private Gtk.Alignment alignment7;
        
        private Gtk.SpinButton spnUpdateTime;
        
        private Gtk.Alignment alignment6;
        
        private Gtk.Label label3;
        
        private Gtk.Alignment alignment5;
        
        private Gtk.ComboBox cboUpdateTimeType;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget GUPdotNET.frmUpdateConfirm
            this.Name = "GUPdotNET.frmUpdateConfirm";
            this.Title = Mono.Unix.Catalog.GetString("GUPdotNET Update Options");
            this.Icon = Gdk.Pixbuf.LoadFromResource("update_medium.png");
            this.TypeHint = ((Gdk.WindowTypeHint)(1));
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            this.BorderWidth = ((uint)(3));
            this.AllowShrink = true;
            // Internal child GUPdotNET.frmUpdateConfirm.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.alignment1 = new Gtk.Alignment(0.8F, 0.5F, 0.01F, 1F);
            this.alignment1.Name = "alignment1";
            this.alignment1.TopPadding = ((uint)(3));
            this.alignment1.BottomPadding = ((uint)(3));
            // Container child alignment1.Gtk.Container+ContainerChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("<span size=\"x-large\"><b>Update Options</b></span>");
            this.label1.UseMarkup = true;
            this.alignment1.Add(this.label1);
            this.hbox2.Add(this.alignment1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox2[this.alignment1]));
            w3.Position = 0;
            // Container child hbox2.Gtk.Box+BoxChild
            this.alignment10 = new Gtk.Alignment(0.99F, 0.01F, 0.01F, 0.01F);
            this.alignment10.Name = "alignment10";
            // Container child alignment10.Gtk.Container+ContainerChild
            this.btnAbout = new Gtk.Button();
            this.btnAbout.CanFocus = true;
            this.btnAbout.Name = "btnAbout";
            this.btnAbout.Relief = ((Gtk.ReliefStyle)(2));
            this.btnAbout.Xalign = 0.01F;
            this.btnAbout.Yalign = 0.99F;
            // Container child btnAbout.Gtk.Container+ContainerChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 0.01F;
            this.label4.Yalign = 0.99F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("<span size=\"x-small\" color=\"blue\"><u>About GUPdotNET</u></span>");
            this.label4.UseMarkup = true;
            this.btnAbout.Add(this.label4);
            this.btnAbout.Label = null;
            this.alignment10.Add(this.btnAbout);
            this.hbox2.Add(this.alignment10);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.alignment10]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            this.vbox2.Add(this.hbox2);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment2 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment2.Name = "alignment2";
            // Container child alignment2.Gtk.Container+ContainerChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.alignment2.Add(this.hseparator1);
            this.vbox2.Add(this.alignment2);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox2[this.alignment2]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment3 = new Gtk.Alignment(0.5F, 0.5F, 0.5F, 1F);
            this.alignment3.Name = "alignment3";
            this.alignment3.LeftPadding = ((uint)(25));
            this.alignment3.TopPadding = ((uint)(3));
            this.alignment3.RightPadding = ((uint)(25));
            this.alignment3.BottomPadding = ((uint)(3));
            // Container child alignment3.Gtk.Container+ContainerChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment2.Name = "GtkAlignment2";
            this.GtkAlignment2.LeftPadding = ((uint)(12));
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            this.alignment4 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment4.Name = "alignment4";
            // Container child alignment4.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.alignment8 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment8.Name = "alignment8";
            // Container child alignment8.Gtk.Container+ContainerChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Check for updates ");
            this.alignment8.Add(this.label2);
            this.hbox1.Add(this.alignment8);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox1[this.alignment8]));
            w11.Position = 0;
            w11.Expand = false;
            w11.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.alignment7 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment7.Name = "alignment7";
            // Container child alignment7.Gtk.Container+ContainerChild
            this.spnUpdateTime = new Gtk.SpinButton(1, 100, 1);
            this.spnUpdateTime.CanFocus = true;
            this.spnUpdateTime.Name = "spnUpdateTime";
            this.spnUpdateTime.Adjustment.PageIncrement = 10;
            this.spnUpdateTime.ClimbRate = 1;
            this.spnUpdateTime.Numeric = true;
            this.spnUpdateTime.SnapToTicks = true;
            this.spnUpdateTime.Value = 1;
            this.alignment7.Add(this.spnUpdateTime);
            this.hbox1.Add(this.alignment7);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox1[this.alignment7]));
            w13.Position = 1;
            w13.Expand = false;
            w13.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.alignment6 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment6.Name = "alignment6";
            // Container child alignment6.Gtk.Container+ContainerChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString(" every ");
            this.alignment6.Add(this.label3);
            this.hbox1.Add(this.alignment6);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox1[this.alignment6]));
            w15.Position = 2;
            w15.Expand = false;
            w15.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.alignment5 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment5.Name = "alignment5";
            // Container child alignment5.Gtk.Container+ContainerChild
            this.cboUpdateTimeType = Gtk.ComboBox.NewText();
            this.cboUpdateTimeType.AppendText(Mono.Unix.Catalog.GetString("Day"));
            this.cboUpdateTimeType.AppendText(Mono.Unix.Catalog.GetString("Week"));
            this.cboUpdateTimeType.AppendText(Mono.Unix.Catalog.GetString("Month"));
            this.cboUpdateTimeType.AppendText(Mono.Unix.Catalog.GetString("Never"));
            this.cboUpdateTimeType.Name = "cboUpdateTimeType";
            this.cboUpdateTimeType.Active = 0;
            this.alignment5.Add(this.cboUpdateTimeType);
            this.hbox1.Add(this.alignment5);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox1[this.alignment5]));
            w17.Position = 3;
            w17.Expand = false;
            w17.Fill = false;
            this.alignment4.Add(this.hbox1);
            this.GtkAlignment2.Add(this.alignment4);
            this.frame1.Add(this.GtkAlignment2);
            this.alignment3.Add(this.frame1);
            this.vbox2.Add(this.alignment3);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.vbox2[this.alignment3]));
            w22.Position = 2;
            w22.Expand = false;
            w22.Fill = false;
            w1.Add(this.vbox2);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(w1[this.vbox2]));
            w23.Position = 0;
            w23.Expand = false;
            w23.Fill = false;
            // Internal child GUPdotNET.frmUpdateConfirm.ActionArea
            Gtk.HButtonBox w24 = this.ActionArea;
            w24.Name = "dialog1_ActionArea";
            w24.Spacing = 6;
            w24.BorderWidth = ((uint)(5));
            w24.LayoutStyle = ((Gtk.ButtonBoxStyle)(1));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w25 = ((Gtk.ButtonBox.ButtonBoxChild)(w24[this.buttonCancel]));
            w25.Expand = false;
            w25.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w26 = ((Gtk.ButtonBox.ButtonBoxChild)(w24[this.buttonOk]));
            w26.Position = 1;
            w26.Expand = false;
            w26.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 428;
            this.DefaultHeight = 150;
            this.Show();
            this.btnAbout.Clicked += new System.EventHandler(this.OnBtnAboutClicked);
            this.buttonCancel.Clicked += new System.EventHandler(this.OnButtonCancelClicked);
            this.buttonOk.Clicked += new System.EventHandler(this.OnButtonOkClicked);
        }
    }
}
