// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ThudSharp {
    
    
    public partial class BoardPiece {
        
        private Gtk.Fixed fxContainer;
        
        private Gtk.Image imgBackground;
        
        private Gtk.Image imgMovable;
        
        private Gtk.EventBox eventbox1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ThudSharp.BoardPiece
            Stetic.BinContainer.Attach(this);
            this.Name = "ThudSharp.BoardPiece";
            // Container child ThudSharp.BoardPiece.Gtk.Container+ContainerChild
            this.fxContainer = new Gtk.Fixed();
            this.fxContainer.WidthRequest = 45;
            this.fxContainer.HeightRequest = 45;
            this.fxContainer.Name = "fxContainer";
            this.fxContainer.HasWindow = false;
            // Container child fxContainer.Gtk.Fixed+FixedChild
            this.imgBackground = new Gtk.Image();
            this.imgBackground.WidthRequest = 45;
            this.imgBackground.HeightRequest = 45;
            this.imgBackground.Events = ((Gdk.EventMask)(790526));
            this.imgBackground.Name = "imgBackground";
            this.fxContainer.Add(this.imgBackground);
            // Container child fxContainer.Gtk.Fixed+FixedChild
            this.imgMovable = new Gtk.Image();
            this.imgMovable.WidthRequest = 45;
            this.imgMovable.HeightRequest = 45;
            this.imgMovable.Events = ((Gdk.EventMask)(790526));
            this.imgMovable.Name = "imgMovable";
            this.imgMovable.Xpad = 2;
            this.imgMovable.Ypad = 2;
            this.fxContainer.Add(this.imgMovable);
            // Container child fxContainer.Gtk.Fixed+FixedChild
            this.eventbox1 = new Gtk.EventBox();
            this.eventbox1.WidthRequest = 43;
            this.eventbox1.HeightRequest = 43;
            this.eventbox1.Name = "eventbox1";
            this.eventbox1.AboveChild = true;
            this.eventbox1.VisibleWindow = false;
            this.fxContainer.Add(this.eventbox1);
            Gtk.Fixed.FixedChild w3 = ((Gtk.Fixed.FixedChild)(this.fxContainer[this.eventbox1]));
            w3.X = 2;
            w3.Y = 2;
            this.Add(this.fxContainer);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
