// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoBPMonitor {
	
	
	public partial class frmBackupRestore : Gtk.Dialog {
		
		public frmBackupRestore() {
			this.Build();
		}
		
		protected virtual void OnBtnClearLogClicked(object sender, System.EventArgs e) {
		}

		protected virtual void OnCbxAllToggled (object sender, System.EventArgs e)
		{
		}

		protected virtual void OnBtnCancelClicked (object sender, System.EventArgs e)
		{
		}

		protected virtual void OnBtnRunClicked (object sender, System.EventArgs e)
		{
		}

		protected virtual void OnBtnCloseClicked (object sender, System.EventArgs e)
		{
		}
	}
}
