// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GUPdotNET {
    
    
    public partial class frmUpdateDownload {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Label lblProgramTitle;
        
        private Gtk.Label lblUpdateMessage;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.ProgressBar progressbar1;
        
        private Gtk.Alignment alignment2;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.Button btnCancel;
        
        private Gtk.Button btnOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget GUPdotNET.frmUpdateDownload
            this.Name = "GUPdotNET.frmUpdateDownload";
            this.TypeHint = ((Gdk.WindowTypeHint)(1));
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.AllowShrink = true;
            this.DestroyWithParent = true;
            this.HasSeparator = false;
            // Internal child GUPdotNET.frmUpdateDownload.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.lblProgramTitle = new Gtk.Label();
            this.lblProgramTitle.Name = "lblProgramTitle";
            this.lblProgramTitle.LabelProp = Mono.Unix.Catalog.GetString("null");
            this.lblProgramTitle.UseMarkup = true;
            this.vbox2.Add(this.lblProgramTitle);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.lblProgramTitle]));
            w2.Position = 0;
            // Container child vbox2.Gtk.Box+BoxChild
            this.lblUpdateMessage = new Gtk.Label();
            this.lblUpdateMessage.Name = "lblUpdateMessage";
            this.lblUpdateMessage.LabelProp = Mono.Unix.Catalog.GetString("null");
            this.lblUpdateMessage.Justify = ((Gtk.Justification)(2));
            this.vbox2.Add(this.lblUpdateMessage);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.lblUpdateMessage]));
            w3.Position = 1;
            w3.Padding = ((uint)(5));
            // Container child vbox2.Gtk.Box+BoxChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.vbox2.Add(this.hseparator1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.hseparator1]));
            w4.Position = 2;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.alignment1.LeftPadding = ((uint)(10));
            this.alignment1.RightPadding = ((uint)(10));
            // Container child alignment1.Gtk.Container+ContainerChild
            this.progressbar1 = new Gtk.ProgressBar();
            this.progressbar1.WidthRequest = 98;
            this.progressbar1.Name = "progressbar1";
            this.progressbar1.Text = Mono.Unix.Catalog.GetString("Starting Download");
            this.progressbar1.Ellipsize = ((Pango.EllipsizeMode)(1));
            this.alignment1.Add(this.progressbar1);
            this.vbox2.Add(this.alignment1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox2[this.alignment1]));
            w6.Position = 3;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment2 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment2.Name = "alignment2";
            // Container child alignment2.Gtk.Container+ContainerChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.alignment2.Add(this.hseparator2);
            this.vbox2.Add(this.alignment2);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox2[this.alignment2]));
            w8.Position = 4;
            w8.Expand = false;
            w8.Fill = false;
            w1.Add(this.vbox2);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(w1[this.vbox2]));
            w9.Position = 0;
            // Internal child GUPdotNET.frmUpdateDownload.ActionArea
            Gtk.HButtonBox w10 = this.ActionArea;
            w10.Name = "dialog1_ActionArea";
            w10.Spacing = 6;
            w10.BorderWidth = ((uint)(5));
            w10.LayoutStyle = ((Gtk.ButtonBoxStyle)(1));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.btnCancel = new Gtk.Button();
            this.btnCancel.CanDefault = true;
            this.btnCancel.CanFocus = true;
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.UseStock = true;
            this.btnCancel.UseUnderline = true;
            this.btnCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.btnCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w11 = ((Gtk.ButtonBox.ButtonBoxChild)(w10[this.btnCancel]));
            w11.Expand = false;
            w11.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.btnOk = new Gtk.Button();
            this.btnOk.CanFocus = true;
            this.btnOk.Name = "btnOk";
            this.btnOk.UseStock = true;
            this.btnOk.UseUnderline = true;
            this.btnOk.Label = "gtk-ok";
            this.AddActionWidget(this.btnOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w12 = ((Gtk.ButtonBox.ButtonBoxChild)(w10[this.btnOk]));
            w12.Position = 1;
            w12.Expand = false;
            w12.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 373;
            this.DefaultHeight = 182;
            this.Show();
            this.btnCancel.Clicked += new System.EventHandler(this.OnButtonCancelClicked);
            this.btnOk.Clicked += new System.EventHandler(this.OnBtnOkClicked);
        }
    }
}
