
// This file has been generated by the GUI designer. Do not modify.
namespace CMYControls
{
	public partial class QuickDate
	{
		private global::Gtk.Frame frame1;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.Entry txtQuickDate;

		private global::Gtk.Button btnShowCalendar;

		private global::Gtk.Image image1;

		private global::Gtk.Button btnClearDate;

		private global::Gtk.Image image2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CMYControls.QuickDate
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CMYControls.QuickDate";
			// Container child CMYControls.QuickDate.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.CanDefault = true;
			this.frame1.CanFocus = true;
			this.frame1.Name = "frame1";
			this.frame1.BorderWidth = ((uint)(2));
			// Container child frame1.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.CanDefault = true;
			this.fixed3.CanFocus = true;
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.txtQuickDate = new global::Gtk.Entry ();
			this.txtQuickDate.WidthRequest = 150;
			this.txtQuickDate.CanFocus = true;
			this.txtQuickDate.Name = "txtQuickDate";
			this.txtQuickDate.IsEditable = false;
			this.fixed3.Add (this.txtQuickDate);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.txtQuickDate]));
			w1.X = 2;
			w1.Y = 1;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.btnShowCalendar = new global::Gtk.Button ();
			this.btnShowCalendar.HeightRequest = 22;
			this.btnShowCalendar.CanFocus = true;
			this.btnShowCalendar.Name = "btnShowCalendar";
			// Container child btnShowCalendar.Gtk.Container+ContainerChild
			this.image1 = new global::Gtk.Image ();
			this.image1.WidthRequest = 12;
			this.image1.HeightRequest = 12;
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("QuickDate.png");
			this.btnShowCalendar.Add (this.image1);
			this.btnShowCalendar.Label = null;
			this.fixed3.Add (this.btnShowCalendar);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.btnShowCalendar]));
			w3.X = 176;
			w3.Y = 1;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.btnClearDate = new global::Gtk.Button ();
			this.btnClearDate.HeightRequest = 22;
			this.btnClearDate.CanFocus = true;
			this.btnClearDate.Name = "btnClearDate";
			// Container child btnClearDate.Gtk.Container+ContainerChild
			this.image2 = new global::Gtk.Image ();
			this.image2.WidthRequest = 12;
			this.image2.HeightRequest = 12;
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ClearDate.png");
			this.btnClearDate.Add (this.image2);
			this.btnClearDate.Label = null;
			this.fixed3.Add (this.btnClearDate);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.btnClearDate]));
			w5.X = 152;
			w5.Y = 1;
			this.frame1.Add (this.fixed3);
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
