//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoBPMonitor {
    
    
    public partial class frmOptions {
        
        private Gtk.Alignment GtkAlignment2;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Alignment alignment9;
        
        private Gtk.Label label4;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Table table3;
        
        private Gtk.Alignment alignment11;
        
        private Gtk.Label label6;
        
        private Gtk.Alignment alignment12;
        
        private Gtk.SpinButton spnDefaultHistory;
        
        private Gtk.Alignment alignment5;
        
        private Gtk.Label label2;
        
        private Gtk.Alignment alignment6;
        
        private Gtk.Label label3;
        
        private Gtk.CheckButton cbxLimitRecords;
        
        private Gtk.CheckButton cbxLogErrors;
        
        private Gtk.Button btnCancel;
        
        private Gtk.Button btnOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoBPMonitor.frmOptions
            this.WidthRequest = 450;
            this.Name = "MonoBPMonitor.frmOptions";
            this.Title = Mono.Unix.Catalog.GetString("Options");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-preferences", Gtk.IconSize.Dialog, 48);
            this.TypeHint = ((Gdk.WindowTypeHint)(1));
            this.WindowPosition = ((Gtk.WindowPosition)(1));
            this.Modal = true;
            this.BorderWidth = ((uint)(4));
            this.Resizable = false;
            this.AllowGrow = false;
            this.DefaultWidth = 450;
            // Internal child MonoBPMonitor.frmOptions.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment2.Name = "GtkAlignment2";
            this.GtkAlignment2.LeftPadding = ((uint)(12));
            this.GtkAlignment2.TopPadding = ((uint)(6));
            this.GtkAlignment2.RightPadding = ((uint)(6));
            this.GtkAlignment2.BottomPadding = ((uint)(10));
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.alignment9 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment9.Name = "alignment9";
            this.alignment9.TopPadding = ((uint)(6));
            this.alignment9.BottomPadding = ((uint)(4));
            // Container child alignment9.Gtk.Container+ContainerChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("<big><b>Options</b></big>");
            this.label4.UseMarkup = true;
            this.alignment9.Add(this.label4);
            this.vbox3.Add(this.alignment9);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.alignment9]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            // Container child alignment1.Gtk.Container+ContainerChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.alignment1.Add(this.hseparator1);
            this.vbox3.Add(this.alignment1);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox3[this.alignment1]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.table3 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.alignment11 = new Gtk.Alignment(0.98F, 0.5F, 0.01F, 1F);
            this.alignment11.Name = "alignment11";
            this.alignment11.LeftPadding = ((uint)(30));
            // Container child alignment11.Gtk.Container+ContainerChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Default history shown at start up:");
            this.alignment11.Add(this.label6);
            this.table3.Add(this.alignment11);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table3[this.alignment11]));
            w7.TopAttach = ((uint)(2));
            w7.BottomAttach = ((uint)(3));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.alignment12 = new Gtk.Alignment(0.02F, 0.5F, 0.01F, 1F);
            this.alignment12.Name = "alignment12";
            // Container child alignment12.Gtk.Container+ContainerChild
            this.spnDefaultHistory = new Gtk.SpinButton(0, 100, 1);
            this.spnDefaultHistory.CanFocus = true;
            this.spnDefaultHistory.Name = "spnDefaultHistory";
            this.spnDefaultHistory.Adjustment.PageIncrement = 10;
            this.spnDefaultHistory.ClimbRate = 1;
            this.spnDefaultHistory.Numeric = true;
            this.spnDefaultHistory.Value = 30;
            this.alignment12.Add(this.spnDefaultHistory);
            this.table3.Add(this.alignment12);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table3[this.alignment12]));
            w9.TopAttach = ((uint)(2));
            w9.BottomAttach = ((uint)(3));
            w9.LeftAttach = ((uint)(1));
            w9.RightAttach = ((uint)(2));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.alignment5 = new Gtk.Alignment(0.01F, 0.5F, 0.98F, 1F);
            this.alignment5.Name = "alignment5";
            // Container child alignment5.Gtk.Container+ContainerChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0.98F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Save Errors:");
            this.alignment5.Add(this.label2);
            this.table3.Add(this.alignment5);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table3[this.alignment5]));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.alignment6 = new Gtk.Alignment(0.01F, 0.5F, 0.98F, 1F);
            this.alignment6.Name = "alignment6";
            // Container child alignment6.Gtk.Container+ContainerChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 0.98F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Limit amount of readings displayed:");
            this.alignment6.Add(this.label3);
            this.table3.Add(this.alignment6);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table3[this.alignment6]));
            w13.TopAttach = ((uint)(1));
            w13.BottomAttach = ((uint)(2));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.cbxLimitRecords = new Gtk.CheckButton();
            this.cbxLimitRecords.Name = "cbxLimitRecords";
            this.cbxLimitRecords.Label = "";
            this.cbxLimitRecords.Active = true;
            this.cbxLimitRecords.DrawIndicator = true;
            this.cbxLimitRecords.FocusOnClick = false;
            this.cbxLimitRecords.Xalign = 0.01F;
            this.cbxLimitRecords.Yalign = 0.01F;
            this.table3.Add(this.cbxLimitRecords);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table3[this.cbxLimitRecords]));
            w14.TopAttach = ((uint)(1));
            w14.BottomAttach = ((uint)(2));
            w14.LeftAttach = ((uint)(1));
            w14.RightAttach = ((uint)(2));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.cbxLogErrors = new Gtk.CheckButton();
            this.cbxLogErrors.Name = "cbxLogErrors";
            this.cbxLogErrors.Label = "";
            this.cbxLogErrors.Active = true;
            this.cbxLogErrors.DrawIndicator = true;
            this.cbxLogErrors.FocusOnClick = false;
            this.cbxLogErrors.Xalign = 0.01F;
            this.cbxLogErrors.Yalign = 0.01F;
            this.table3.Add(this.cbxLogErrors);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table3[this.cbxLogErrors]));
            w15.LeftAttach = ((uint)(1));
            w15.RightAttach = ((uint)(2));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox3.Add(this.table3);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox3[this.table3]));
            w16.Position = 2;
            w16.Expand = false;
            w16.Fill = false;
            this.GtkAlignment2.Add(this.vbox3);
            w1.Add(this.GtkAlignment2);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(w1[this.GtkAlignment2]));
            w18.Position = 0;
            w18.Expand = false;
            w18.Fill = false;
            // Internal child MonoBPMonitor.frmOptions.ActionArea
            Gtk.HButtonBox w19 = this.ActionArea;
            w19.Name = "dialog1_ActionArea";
            w19.Spacing = 6;
            w19.BorderWidth = ((uint)(5));
            w19.LayoutStyle = ((Gtk.ButtonBoxStyle)(1));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.btnCancel = new Gtk.Button();
            this.btnCancel.CanDefault = true;
            this.btnCancel.CanFocus = true;
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.UseStock = true;
            this.btnCancel.UseUnderline = true;
            this.btnCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.btnCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w20 = ((Gtk.ButtonBox.ButtonBoxChild)(w19[this.btnCancel]));
            w20.Expand = false;
            w20.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.btnOk = new Gtk.Button();
            this.btnOk.CanFocus = true;
            this.btnOk.Name = "btnOk";
            this.btnOk.UseStock = true;
            this.btnOk.UseUnderline = true;
            this.btnOk.Label = "gtk-ok";
            this.AddActionWidget(this.btnOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w21 = ((Gtk.ButtonBox.ButtonBoxChild)(w19[this.btnOk]));
            w21.Position = 1;
            w21.Expand = false;
            w21.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultHeight = 204;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.cbxLimitRecords.Toggled += new System.EventHandler(this.OnCbxLimitRecordsToggled);
            this.btnCancel.Clicked += new System.EventHandler(this.OnBtnCancelClicked);
            this.btnOk.Clicked += new System.EventHandler(this.OnBtnOkClicked);
        }
    }
}
