// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoBPMonitor {
    
    
    public partial class frmOptions {
        
        private Gtk.Alignment alignment1;
        
        private Gtk.Notebook notebook1;
        
        private Gtk.Alignment GtkAlignment2;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Table table3;
        
        private Gtk.Alignment alignment11;
        
        private Gtk.Label label6;
        
        private Gtk.Alignment alignment12;
        
        private Gtk.SpinButton spnDefaultHistory;
        
        private Gtk.Alignment alignment5;
        
        private Gtk.Label label2;
        
        private Gtk.Alignment alignment6;
        
        private Gtk.Label label3;
        
        private Gtk.CheckButton cbxLimitRecords;
        
        private Gtk.CheckButton cbxLogErrors;
        
        private Gtk.Label label1;
        
        private Gtk.Alignment alignment21;
        
        private Gtk.VBox vbox6;
        
        private Gtk.Alignment alignment26;
        
        private Gtk.Frame frame3;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.Table table2;
        
        private Gtk.Alignment alignment32;
        
        private Gtk.Label label16;
        
        private Gtk.Alignment alignment34;
        
        private Gtk.Label lblMonoBPMonitorVersion;
        
        private Gtk.Alignment alignment35;
        
        private Gtk.Label lblDatabaseVersion;
        
        private Gtk.Alignment alignment36;
        
        private Gtk.Label label11;
        
        private Gtk.Alignment alignment37;
        
        private Gtk.Label lblGUPdotNETText;
        
        private Gtk.Alignment alignment38;
        
        private Gtk.Label lblGUPdotNETVersion;
        
        private Gtk.Alignment alignment39;
        
        private Gtk.Label label13;
        
        private Gtk.Alignment alignment40;
        
        private Gtk.Label lblOptionsFileVersion;
        
        private Gtk.Label GtkLabel12;
        
        private Gtk.Alignment alignment29;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.Alignment alignment25;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Alignment alignment41;
        
        private Gtk.Label label14;
        
        private Gtk.Alignment alignment27;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Alignment alignment24;
        
        private Gtk.Label lblDatabaseLocation;
        
        private Gtk.Label label8;
        
        private Gtk.Button button10;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoBPMonitor.frmOptions
            this.WidthRequest = 650;
            this.Name = "MonoBPMonitor.frmOptions";
            this.Title = Mono.Unix.Catalog.GetString("Options");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-preferences", Gtk.IconSize.Dialog, 48);
            this.TypeHint = ((Gdk.WindowTypeHint)(1));
            this.WindowPosition = ((Gtk.WindowPosition)(2));
            this.Modal = true;
            this.BorderWidth = ((uint)(4));
            this.Resizable = false;
            this.AllowGrow = false;
            this.DefaultWidth = 650;
            // Internal child MonoBPMonitor.frmOptions.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            // Container child alignment1.Gtk.Container+ContainerChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 1;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment2.Name = "GtkAlignment2";
            this.GtkAlignment2.LeftPadding = ((uint)(12));
            this.GtkAlignment2.TopPadding = ((uint)(25));
            this.GtkAlignment2.RightPadding = ((uint)(6));
            this.GtkAlignment2.BottomPadding = ((uint)(10));
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.table3 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.alignment11 = new Gtk.Alignment(0.98F, 0.5F, 0.01F, 1F);
            this.alignment11.Name = "alignment11";
            this.alignment11.LeftPadding = ((uint)(30));
            // Container child alignment11.Gtk.Container+ContainerChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Default history shown at start up:");
            this.alignment11.Add(this.label6);
            this.table3.Add(this.alignment11);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table3[this.alignment11]));
            w3.TopAttach = ((uint)(2));
            w3.BottomAttach = ((uint)(3));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.alignment12 = new Gtk.Alignment(0.02F, 0.5F, 0.01F, 1F);
            this.alignment12.Name = "alignment12";
            // Container child alignment12.Gtk.Container+ContainerChild
            this.spnDefaultHistory = new Gtk.SpinButton(0, 100, 1);
            this.spnDefaultHistory.CanFocus = true;
            this.spnDefaultHistory.Name = "spnDefaultHistory";
            this.spnDefaultHistory.Adjustment.PageIncrement = 10;
            this.spnDefaultHistory.ClimbRate = 1;
            this.spnDefaultHistory.Numeric = true;
            this.spnDefaultHistory.Value = 30;
            this.alignment12.Add(this.spnDefaultHistory);
            this.table3.Add(this.alignment12);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table3[this.alignment12]));
            w5.TopAttach = ((uint)(2));
            w5.BottomAttach = ((uint)(3));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.alignment5 = new Gtk.Alignment(0.01F, 0.5F, 0.98F, 1F);
            this.alignment5.Name = "alignment5";
            // Container child alignment5.Gtk.Container+ContainerChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0.98F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Save Errors:");
            this.alignment5.Add(this.label2);
            this.table3.Add(this.alignment5);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table3[this.alignment5]));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.alignment6 = new Gtk.Alignment(0.01F, 0.5F, 0.98F, 1F);
            this.alignment6.Name = "alignment6";
            // Container child alignment6.Gtk.Container+ContainerChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 0.98F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Limit amount of readings displayed:");
            this.alignment6.Add(this.label3);
            this.table3.Add(this.alignment6);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table3[this.alignment6]));
            w9.TopAttach = ((uint)(1));
            w9.BottomAttach = ((uint)(2));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.cbxLimitRecords = new Gtk.CheckButton();
            this.cbxLimitRecords.Name = "cbxLimitRecords";
            this.cbxLimitRecords.Label = "";
            this.cbxLimitRecords.Active = true;
            this.cbxLimitRecords.DrawIndicator = true;
            this.cbxLimitRecords.FocusOnClick = false;
            this.cbxLimitRecords.Xalign = 0.01F;
            this.cbxLimitRecords.Yalign = 0.01F;
            this.table3.Add(this.cbxLimitRecords);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table3[this.cbxLimitRecords]));
            w10.TopAttach = ((uint)(1));
            w10.BottomAttach = ((uint)(2));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.cbxLogErrors = new Gtk.CheckButton();
            this.cbxLogErrors.Name = "cbxLogErrors";
            this.cbxLogErrors.Label = "";
            this.cbxLogErrors.Active = true;
            this.cbxLogErrors.DrawIndicator = true;
            this.cbxLogErrors.FocusOnClick = false;
            this.cbxLogErrors.Xalign = 0.01F;
            this.cbxLogErrors.Yalign = 0.01F;
            this.table3.Add(this.cbxLogErrors);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table3[this.cbxLogErrors]));
            w11.LeftAttach = ((uint)(1));
            w11.RightAttach = ((uint)(2));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox3.Add(this.table3);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox3[this.table3]));
            w12.Position = 0;
            w12.Expand = false;
            w12.Fill = false;
            this.GtkAlignment2.Add(this.vbox3);
            this.notebook1.Add(this.GtkAlignment2);
            // Notebook tab
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xpad = 6;
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("<b>Options</b>");
            this.label1.UseMarkup = true;
            this.notebook1.SetTabLabel(this.GtkAlignment2, this.label1);
            this.label1.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.alignment21 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment21.Name = "alignment21";
            // Container child alignment21.Gtk.Container+ContainerChild
            this.vbox6 = new Gtk.VBox();
            this.vbox6.Name = "vbox6";
            this.vbox6.Spacing = 6;
            // Container child vbox6.Gtk.Box+BoxChild
            this.alignment26 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment26.Name = "alignment26";
            this.alignment26.LeftPadding = ((uint)(8));
            this.alignment26.TopPadding = ((uint)(15));
            this.alignment26.RightPadding = ((uint)(8));
            this.alignment26.BottomPadding = ((uint)(12));
            // Container child alignment26.Gtk.Container+ContainerChild
            this.frame3 = new Gtk.Frame();
            this.frame3.Name = "frame3";
            // Container child frame3.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(36));
            this.GtkAlignment1.RightPadding = ((uint)(20));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.table2 = new Gtk.Table(((uint)(4)), ((uint)(2)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            this.table2.BorderWidth = ((uint)(10));
            // Container child table2.Gtk.Table+TableChild
            this.alignment32 = new Gtk.Alignment(0.98F, 0.5F, 0.01F, 1F);
            this.alignment32.Name = "alignment32";
            // Container child alignment32.Gtk.Container+ContainerChild
            this.label16 = new Gtk.Label();
            this.label16.Name = "label16";
            this.label16.LabelProp = Mono.Unix.Catalog.GetString("MonoBPMonitorr:");
            this.alignment32.Add(this.label16);
            this.table2.Add(this.alignment32);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table2[this.alignment32]));
            w16.XOptions = ((Gtk.AttachOptions)(4));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.alignment34 = new Gtk.Alignment(0.04F, 0.5F, 0.01F, 1F);
            this.alignment34.Name = "alignment34";
            // Container child alignment34.Gtk.Container+ContainerChild
            this.lblMonoBPMonitorVersion = new Gtk.Label();
            this.lblMonoBPMonitorVersion.Name = "lblMonoBPMonitorVersion";
            this.lblMonoBPMonitorVersion.LabelProp = Mono.Unix.Catalog.GetString("None");
            this.alignment34.Add(this.lblMonoBPMonitorVersion);
            this.table2.Add(this.alignment34);
            Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table2[this.alignment34]));
            w18.LeftAttach = ((uint)(1));
            w18.RightAttach = ((uint)(2));
            w18.XOptions = ((Gtk.AttachOptions)(4));
            w18.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.alignment35 = new Gtk.Alignment(0.04F, 0.5F, 0.01F, 1F);
            this.alignment35.Name = "alignment35";
            // Container child alignment35.Gtk.Container+ContainerChild
            this.lblDatabaseVersion = new Gtk.Label();
            this.lblDatabaseVersion.Name = "lblDatabaseVersion";
            this.lblDatabaseVersion.LabelProp = Mono.Unix.Catalog.GetString("None");
            this.alignment35.Add(this.lblDatabaseVersion);
            this.table2.Add(this.alignment35);
            Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table2[this.alignment35]));
            w20.TopAttach = ((uint)(1));
            w20.BottomAttach = ((uint)(2));
            w20.LeftAttach = ((uint)(1));
            w20.RightAttach = ((uint)(2));
            w20.XOptions = ((Gtk.AttachOptions)(4));
            w20.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.alignment36 = new Gtk.Alignment(0.98F, 0.5F, 0.01F, 1F);
            this.alignment36.Name = "alignment36";
            // Container child alignment36.Gtk.Container+ContainerChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("Database Version:");
            this.alignment36.Add(this.label11);
            this.table2.Add(this.alignment36);
            Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table2[this.alignment36]));
            w22.TopAttach = ((uint)(1));
            w22.BottomAttach = ((uint)(2));
            w22.XOptions = ((Gtk.AttachOptions)(4));
            w22.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.alignment37 = new Gtk.Alignment(0.98F, 0.5F, 0.01F, 1F);
            this.alignment37.Name = "alignment37";
            // Container child alignment37.Gtk.Container+ContainerChild
            this.lblGUPdotNETText = new Gtk.Label();
            this.lblGUPdotNETText.Name = "lblGUPdotNETText";
            this.lblGUPdotNETText.LabelProp = Mono.Unix.Catalog.GetString("GUPdotNET (<i>Updater</i>):");
            this.lblGUPdotNETText.UseMarkup = true;
            this.alignment37.Add(this.lblGUPdotNETText);
            this.table2.Add(this.alignment37);
            Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table2[this.alignment37]));
            w24.TopAttach = ((uint)(3));
            w24.BottomAttach = ((uint)(4));
            w24.XOptions = ((Gtk.AttachOptions)(4));
            w24.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.alignment38 = new Gtk.Alignment(0.04F, 0.5F, 0.01F, 1F);
            this.alignment38.Name = "alignment38";
            // Container child alignment38.Gtk.Container+ContainerChild
            this.lblGUPdotNETVersion = new Gtk.Label();
            this.lblGUPdotNETVersion.Name = "lblGUPdotNETVersion";
            this.lblGUPdotNETVersion.LabelProp = Mono.Unix.Catalog.GetString("None");
            this.alignment38.Add(this.lblGUPdotNETVersion);
            this.table2.Add(this.alignment38);
            Gtk.Table.TableChild w26 = ((Gtk.Table.TableChild)(this.table2[this.alignment38]));
            w26.TopAttach = ((uint)(3));
            w26.BottomAttach = ((uint)(4));
            w26.LeftAttach = ((uint)(1));
            w26.RightAttach = ((uint)(2));
            w26.XOptions = ((Gtk.AttachOptions)(4));
            w26.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.alignment39 = new Gtk.Alignment(0.98F, 0.5F, 0.01F, 1F);
            this.alignment39.Name = "alignment39";
            // Container child alignment39.Gtk.Container+ContainerChild
            this.label13 = new Gtk.Label();
            this.label13.Name = "label13";
            this.label13.LabelProp = Mono.Unix.Catalog.GetString("Options File Version:");
            this.alignment39.Add(this.label13);
            this.table2.Add(this.alignment39);
            Gtk.Table.TableChild w28 = ((Gtk.Table.TableChild)(this.table2[this.alignment39]));
            w28.TopAttach = ((uint)(2));
            w28.BottomAttach = ((uint)(3));
            w28.XOptions = ((Gtk.AttachOptions)(4));
            w28.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.alignment40 = new Gtk.Alignment(0.04F, 0.5F, 0.01F, 1F);
            this.alignment40.Name = "alignment40";
            // Container child alignment40.Gtk.Container+ContainerChild
            this.lblOptionsFileVersion = new Gtk.Label();
            this.lblOptionsFileVersion.Name = "lblOptionsFileVersion";
            this.lblOptionsFileVersion.LabelProp = Mono.Unix.Catalog.GetString("None");
            this.alignment40.Add(this.lblOptionsFileVersion);
            this.table2.Add(this.alignment40);
            Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table2[this.alignment40]));
            w30.TopAttach = ((uint)(2));
            w30.BottomAttach = ((uint)(3));
            w30.LeftAttach = ((uint)(1));
            w30.RightAttach = ((uint)(2));
            w30.XOptions = ((Gtk.AttachOptions)(4));
            w30.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment1.Add(this.table2);
            this.frame3.Add(this.GtkAlignment1);
            this.GtkLabel12 = new Gtk.Label();
            this.GtkLabel12.Name = "GtkLabel12";
            this.GtkLabel12.Xpad = 4;
            this.GtkLabel12.LabelProp = Mono.Unix.Catalog.GetString("<b>Version Info</b>");
            this.GtkLabel12.UseMarkup = true;
            this.frame3.LabelWidget = this.GtkLabel12;
            this.alignment26.Add(this.frame3);
            this.vbox6.Add(this.alignment26);
            Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.vbox6[this.alignment26]));
            w34.Position = 0;
            w34.Expand = false;
            w34.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.alignment29 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment29.Name = "alignment29";
            // Container child alignment29.Gtk.Container+ContainerChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.alignment29.Add(this.hseparator2);
            this.vbox6.Add(this.alignment29);
            Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.vbox6[this.alignment29]));
            w36.Position = 1;
            w36.Expand = false;
            w36.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.alignment25 = new Gtk.Alignment(0.03F, 0.5F, 0.01F, 1F);
            this.alignment25.Name = "alignment25";
            // Container child alignment25.Gtk.Container+ContainerChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.alignment41 = new Gtk.Alignment(0.98F, 0.5F, 0.01F, 1F);
            this.alignment41.Name = "alignment41";
            // Container child alignment41.Gtk.Container+ContainerChild
            this.label14 = new Gtk.Label();
            this.label14.Name = "label14";
            this.label14.LabelProp = Mono.Unix.Catalog.GetString("Database Location:");
            this.label14.UseMarkup = true;
            this.alignment41.Add(this.label14);
            this.hbox2.Add(this.alignment41);
            Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.hbox2[this.alignment41]));
            w38.Position = 0;
            w38.Expand = false;
            w38.Fill = false;
            this.alignment25.Add(this.hbox2);
            this.vbox6.Add(this.alignment25);
            Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.vbox6[this.alignment25]));
            w40.Position = 2;
            w40.Expand = false;
            w40.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.alignment27 = new Gtk.Alignment(0.02F, 0.5F, 0.01F, 1F);
            this.alignment27.Name = "alignment27";
            this.alignment27.LeftPadding = ((uint)(24));
            // Container child alignment27.Gtk.Container+ContainerChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.alignment24 = new Gtk.Alignment(0.01F, 0.5F, 0.01F, 1F);
            this.alignment24.Name = "alignment24";
            // Container child alignment24.Gtk.Container+ContainerChild
            this.lblDatabaseLocation = new Gtk.Label();
            this.lblDatabaseLocation.WidthRequest = 350;
            this.lblDatabaseLocation.Name = "lblDatabaseLocation";
            this.lblDatabaseLocation.LabelProp = Mono.Unix.Catalog.GetString("None");
            this.lblDatabaseLocation.Ellipsize = ((Pango.EllipsizeMode)(2));
            this.lblDatabaseLocation.SingleLineMode = true;
            this.alignment24.Add(this.lblDatabaseLocation);
            this.hbox3.Add(this.alignment24);
            Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(this.hbox3[this.alignment24]));
            w42.Position = 0;
            w42.Expand = false;
            w42.Fill = false;
            this.alignment27.Add(this.hbox3);
            this.vbox6.Add(this.alignment27);
            Gtk.Box.BoxChild w44 = ((Gtk.Box.BoxChild)(this.vbox6[this.alignment27]));
            w44.Position = 3;
            w44.Expand = false;
            w44.Fill = false;
            this.alignment21.Add(this.vbox6);
            this.notebook1.Add(this.alignment21);
            Gtk.Notebook.NotebookChild w46 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.alignment21]));
            w46.Position = 1;
            // Notebook tab
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.Xpad = 6;
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("<b>Version Info:</b>");
            this.label8.UseMarkup = true;
            this.notebook1.SetTabLabel(this.alignment21, this.label8);
            this.label8.ShowAll();
            this.alignment1.Add(this.notebook1);
            w1.Add(this.alignment1);
            Gtk.Box.BoxChild w48 = ((Gtk.Box.BoxChild)(w1[this.alignment1]));
            w48.Position = 0;
            w48.Expand = false;
            w48.Fill = false;
            w48.Padding = ((uint)(4));
            // Internal child MonoBPMonitor.frmOptions.ActionArea
            Gtk.HButtonBox w49 = this.ActionArea;
            w49.Sensitive = false;
            w49.Name = "dialog1_ActionArea";
            w49.Spacing = 6;
            w49.BorderWidth = ((uint)(5));
            w49.LayoutStyle = ((Gtk.ButtonBoxStyle)(1));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button10 = new Gtk.Button();
            this.button10.CanFocus = true;
            this.button10.Name = "button10";
            this.button10.UseUnderline = true;
            this.button10.Label = Mono.Unix.Catalog.GetString("GtkButton");
            this.AddActionWidget(this.button10, 0);
            Gtk.ButtonBox.ButtonBoxChild w50 = ((Gtk.ButtonBox.ButtonBoxChild)(w49[this.button10]));
            w50.Expand = false;
            w50.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultHeight = 405;
            w49.Hide();
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.Close += new System.EventHandler(this.OnClose);
            this.cbxLimitRecords.Toggled += new System.EventHandler(this.OnCbxLimitRecordsToggled);
            this.lblDatabaseLocation.Shown += new System.EventHandler(this.OnLblDatabaseLocationShown);
        }
    }
}
