// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BookmarkSharpClient {
    
    
    public partial class frmTagEditor {
        
        private Gtk.VBox vbox2;
        
        private Gtk.ScrolledWindow swTagsEditor;
        
        private Gtk.HButtonBox hbuttonbox2;
        
        private Gtk.Button cmdAdd;
        
        private Gtk.Button cmdRemove;
        
        private Gtk.HSeparator hseparator3;
        
        private Gtk.Button cmdClose;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget BookmarkSharpClient.frmTagEditor
            this.Name = "BookmarkSharpClient.frmTagEditor";
            this.Title = Mono.Unix.Catalog.GetString("Tag Editor");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child BookmarkSharpClient.frmTagEditor.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.swTagsEditor = new Gtk.ScrolledWindow();
            this.swTagsEditor.CanFocus = true;
            this.swTagsEditor.Name = "swTagsEditor";
            this.swTagsEditor.ShadowType = ((Gtk.ShadowType)(1));
            this.vbox2.Add(this.swTagsEditor);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.swTagsEditor]));
            w2.Position = 0;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbuttonbox2 = new Gtk.HButtonBox();
            this.hbuttonbox2.Name = "hbuttonbox2";
            this.hbuttonbox2.LayoutStyle = ((Gtk.ButtonBoxStyle)(1));
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.cmdAdd = new Gtk.Button();
            this.cmdAdd.CanFocus = true;
            this.cmdAdd.Name = "cmdAdd";
            this.cmdAdd.UseStock = true;
            this.cmdAdd.UseUnderline = true;
            this.cmdAdd.Label = "gtk-add";
            this.hbuttonbox2.Add(this.cmdAdd);
            Gtk.ButtonBox.ButtonBoxChild w3 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.cmdAdd]));
            w3.Expand = false;
            w3.Fill = false;
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.cmdRemove = new Gtk.Button();
            this.cmdRemove.CanFocus = true;
            this.cmdRemove.Name = "cmdRemove";
            this.cmdRemove.UseStock = true;
            this.cmdRemove.UseUnderline = true;
            this.cmdRemove.Label = "gtk-remove";
            this.hbuttonbox2.Add(this.cmdRemove);
            Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.cmdRemove]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            this.vbox2.Add(this.hbuttonbox2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox2]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hseparator3 = new Gtk.HSeparator();
            this.hseparator3.Name = "hseparator3";
            this.vbox2.Add(this.hseparator3);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox2[this.hseparator3]));
            w6.Position = 2;
            w6.Expand = false;
            w6.Fill = false;
            w1.Add(this.vbox2);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(w1[this.vbox2]));
            w7.Position = 0;
            // Internal child BookmarkSharpClient.frmTagEditor.ActionArea
            Gtk.HButtonBox w8 = this.ActionArea;
            w8.Name = "dialog1_ActionArea";
            w8.Spacing = 6;
            w8.BorderWidth = ((uint)(5));
            w8.LayoutStyle = ((Gtk.ButtonBoxStyle)(1));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.cmdClose = new Gtk.Button();
            this.cmdClose.CanDefault = true;
            this.cmdClose.CanFocus = true;
            this.cmdClose.Name = "cmdClose";
            this.cmdClose.UseStock = true;
            this.cmdClose.UseUnderline = true;
            this.cmdClose.Label = "gtk-close";
            this.AddActionWidget(this.cmdClose, -7);
            Gtk.ButtonBox.ButtonBoxChild w9 = ((Gtk.ButtonBox.ButtonBoxChild)(w8[this.cmdClose]));
            w9.Expand = false;
            w9.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 458;
            this.DefaultHeight = 408;
            this.Show();
        }
    }
}
